# -*- coding: utf-8 -*-
"""PlanX runtime algorithm matrix: execute every algorithm on a live runtime.

Run it with a QGIS launcher, not with a bare Python::

    C:/OSGeo4W/bin/python-qgis-ltr.bat planx/tests/qgis_runtime_algorithm_matrix.py
    C:/OSGeo4W/bin/python-qgis.bat     planx/tests/qgis_runtime_algorithm_matrix.py

Why this exists
---------------
``smoke_provider_catalog.py`` proves the *catalogue* is coherent - ids, groups,
icons, manual anchors. ``smoke_plugin.py`` loads the plugin and counts
algorithms. Neither runs an algorithm. Neither would notice a tool that raises
on every call, returns without writing its sink, or loses its outputs between
QGIS releases. "Does it load?" is not a test (TRAPS 5.1); this matrix answers
the next question a user asks: "does it run?".

What a green cell means - and what it does not
----------------------------------------------
Each case feeds one algorithm a fixture city generated by ``planx:democity``,
executes it through the Processing framework, and asserts that every declared
output was produced and carries data. A green cell therefore means: *the
algorithm was instantiated, accepted its declared parameters, ran to
completion, and emitted populated outputs on this runtime.*

A green cell does **not** prove the numbers are right. Inputs are wired from
each algorithm's own ``parameterDefinitions()`` - see :func:`_pick_layer`,
:func:`_pick_field` and :func:`_pick_raster` - rather than from 69 hand-written
per-algorithm cases, because a hand-written table silently rots when a parameter
is added. The cost of that choice is that a cell can pass while a parameter was
wired to a defensible-but-wrong fixture. Where the name is ambiguous or two
fixtures are equally plausible, the choice is pinned in ``LAYER_OVERRIDES`` /
``FIELD_BY_PARAM`` / ``RASTER_BY_PARAM``.

Numerical correctness is the job of the engine unit tests (``test_engine.py``)
and of ``smoke_plugin.py``, which checks published figures against their
sources. This matrix is the execution-and-plumbing gate. The one structural
claim it does make about values is that a vector output must contain at least
one feature and a raster output at least one finite, non-nodata pixel - so
"ran but produced nothing" is red, not green.

Every wiring decision for every parameter is recorded in the JSON the run
prints, so those claims are checkable rather than asserted.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import sqlite3
import sys
import tempfile
import time
import traceback
import zipfile
from pathlib import Path

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
os.environ.setdefault("PYTHONUTF8", "1")

PLUGIN_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = PLUGIN_ROOT.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import qgis  # noqa: E402

# The Processing framework ships as one of QGIS's own plugins, not as an
# importable package on the launcher's default sys.path.
_QGIS_PLUGINS = Path(qgis.__file__).resolve().parent.parent / "plugins"
if _QGIS_PLUGINS.is_dir() and str(_QGIS_PLUGINS) not in sys.path:
    sys.path.insert(0, str(_QGIS_PLUGINS))

from qgis.core import (  # noqa: E402
    Qgis,
    QgsApplication,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsFeature,
    QgsField,
    QgsFields,
    QgsGeometry,
    QgsProcessingContext,
    QgsProcessingFeedback,
    QgsProcessingParameterBoolean,
    QgsProcessingParameterCrs,
    QgsProcessingParameterDateTime,
    QgsProcessingParameterDefinition,
    QgsProcessingParameterEnum,
    QgsProcessingParameterExtent,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterField,
    QgsProcessingParameterFile,
    QgsProcessingParameterFileDestination,
    QgsProcessingParameterMultipleLayers,
    QgsProcessingParameterNumber,
    QgsProcessingParameterRasterDestination,
    QgsProcessingParameterRasterLayer,
    QgsProcessingParameterString,
    QgsProcessingParameterVectorLayer,
    QgsProject,
    QgsRasterLayer,
    QgsVectorFileWriter,
    QgsVectorLayer,
    QgsWkbTypes,
)
from qgis.PyQt.QtCore import QDate, QDateTime, QTime, QVariant  # noqa: E402

# The number of algorithms this matrix is expected to cover. The catalog gate
# (smoke_provider_catalog.MIN_EXPECTED_ALGORITHM_COUNT) already guards the
# registry; this one guards that the matrix actually swept it, so a run cannot
# report a clean sweep while quietly covering fewer tools.
MIN_EXPECTED_CASE_COUNT = 74

# Fixture city. Large enough that the tools' default catchments (300-500 m) and
# service-area breaks (250/500/1000 m) land on real geometry rather than on
# empty space; small enough that the per-pixel tools stay inside a sane runtime.
CITY_CRS = "EPSG:3857"
CITY_SEED = 42
CITY_BLOCKS_X = 5
CITY_BLOCKS_Y = 5
CITY_BLOCK_SIZE = 150.0

DOUBLE = QVariant.Double
INT = QVariant.Int
STRING = QVariant.String


def _is_optional(definition) -> bool:
    """QgsProcessingParameterDefinition.FlagOptional across Qt5/Qt6 enums."""
    flags = definition.flags()
    try:
        return bool(flags & QgsProcessingParameterDefinition.Flag.FlagOptional)
    except AttributeError:
        return bool(flags & QgsProcessingParameterDefinition.FlagOptional)


# --------------------------------------------------------------------------
# Fixture schemas
# --------------------------------------------------------------------------
# The demo city ships a deliberately thin schema (a street has an id and a
# length; a building has a height). The tools under test ask for attributes the
# demo generator has no reason to invent - emissions, capacities, ages,
# suitabilities. Rather than edit the shipped generator, the matrix widens each
# fixture with the attributes the tools declare, using values that are constant
# or a simple function of the feature index. The point is that the attribute is
# present, typed and plausible; it is explicitly not a calibrated input.

NETWORK_EXTRA = (
    ("speed", DOUBLE),
    ("lanes", DOUBLE),
    ("aadt", DOUBLE),
    ("infra", STRING),
    ("lts", INT),
    ("volume", DOUBLE),
    ("emission", DOUBLE),
    ("cost", DOUBLE),
    ("score", DOUBLE),
    ("heavy", DOUBLE),
    ("oneway", INT),
    ("fwd_cost", DOUBLE),
    ("rev_cost", DOUBLE),
    ("highway", STRING),
    ("width", DOUBLE),
)

BUILDINGS_EXTRA = (("floors", INT), ("year", INT))

LANDUSE_EXTRA = (
    ("category", STRING),
    ("area_m2", DOUBLE),
    ("far", DOUBLE),
    ("s_residential", DOUBLE),
    ("s_commercial", DOUBLE),
    ("s_green", DOUBLE),
    ("lock", INT),
    ("capacity", DOUBLE),
    ("weight", DOUBLE),
    ("existing", DOUBLE),
    ("district", INT),
)

DEMAND_EXTRA = (
    ("value", DOUBLE),
    ("category", STRING),
    ("zone_id", INT),
    ("production", DOUBLE),
    ("attraction", DOUBLE),
    ("rank", DOUBLE),
    ("jobs", INT),
    ("origin_id", INT),
    ("dest_id", INT),
    ("age", INT),
    ("survival", DOUBLE),
    ("fertility", DOUBLE),
    ("migration", DOUBLE),
    ("dens_ha", DOUBLE),
    # Deliberately no `score` here. planx:accessscore computes a `score` per
    # origin, and a fixture origin layer that already carried one made
    # make_fields rename the computed column to `score_2` - so the layer the
    # report tools read kept the *input's* score under the expected name and
    # every access metric came out identical whichever origins were fed in.
    # planx:democity's own demand layer ships only `pop`, so dropping it also
    # makes the fixture faithful. The underlying fragility is real and is
    # reported to the maintainer rather than papered over here.
)

POIS_EXTRA = (("weight", DOUBLE), ("dest_id", INT))

FACILITIES_EXTRA = (
    ("facility_id", INT),
    ("capacity", DOUBLE),
    ("site_cost", DOUBLE),
    ("existing", DOUBLE),
    ("dest_id", INT),
)

GREEN_EXTRA = (("area_m2", DOUBLE),)

FLOWS_EXTRA = (
    ("flow", DOUBLE),
    ("time_car", DOUBLE),
    ("time_transit", DOUBLE),
    ("cost", DOUBLE),
)


def _geometry_area(feature):
    geometry = feature.geometry()
    if geometry is None or geometry.isEmpty():
        return 0.0
    return float(geometry.area())


def _number(values, key, fallback):
    """A demo attribute by name. By name, not by position: a GeoPackage read
    back through OGR carries its own ``fid`` field ahead of the real ones."""
    value = values.get(key)
    return fallback if value is None else float(value)


def _network_attrs(index, _feature, values):
    length = _number(values, "length_m", 0.0)
    return [
        50.0,                                  # speed
        2.0,                                   # lanes
        1200.0,                                # aadt
        "mixed",                               # infra
        1 + index % 4,                         # lts
        800.0 + float((index * 137) % 900),    # volume
        0.35,                                  # emission
        length,                                # cost
        45.0 + float((index * 7) % 50),        # score
        4.0,                                   # heavy
        0,                                     # oneway
        length,                                # fwd_cost
        length,                                # rev_cost
        "residential",                         # highway
        8.0,                                   # width
    ]


def _building_attrs(index, _feature, values):
    height = _number(values, "height", 6.0)
    return [max(1, int(round(height / 3.0))), 1975 + (index * 3) % 50]


#: The occupancy fixture: what a real city's building layer looks like when it
#: has been prepared for a casualty run, rather than the bare geometry the demo
#: city generates. Cycled rather than random so a run is reproducible.
OCCUPANCY_EXTRA = (
    ("occupancy", STRING),
    ("population", DOUBLE),
    ("units", DOUBLE),
    ("damage_state", STRING),
)
_OCCUPANCY_CYCLE = (
    ("Residential", 1), ("Residential", 4), ("Commercial", 0),
    ("Primary school", 0), ("Industrial", 0), ("Hotel", 0),
)


def _occupancy_attrs(index, _feature, values):
    label, units = _OCCUPANCY_CYCLE[index % len(_OCCUPANCY_CYCLE)]
    floors = max(1, int(round(_number(values, "height", 6.0) / 3.0)))
    return [
        label,
        float(floors * 12),      # population: a screening count, not a survey
        float(units),
        # Cycling the damage state gives the certainty branch all five states,
        # including "none", rather than only the ones a single run would hit.
        ("none", "slight", "moderate", "extensive", "complete")[index % 5],
    ]


#: The six categories the liquefaction model's tables are written for, cycled
#: so one run touches all six branches. Spelled exactly as the model accepts
#: them, which is the point of the fixture: the land-use words an ordinary
#: city layer carries are *not* these, and the tool refuses them on purpose.
_LIQ_CATEGORY_CYCLE = ("Very High", "High", "Moderate", "Low", "Very Low",
                       "None")


def _liq_category_attrs(index, _feature, _values):
    return [_LIQ_CATEGORY_CYCLE[index % len(_LIQ_CATEGORY_CYCLE)]]


#: Water-table depth the susceptibility extra run is pinned to, in metres.
#: Spelled once: the extra run sets the parameter from it and the value check
#: re-derives K_W from it, and a constant written down twice is a check that
#: can drift away from the thing it is checking.
_LIQ_GROUNDWATER_M = 1.524


def _landuse_attrs(index, feature, values):
    use = str(values.get("use") or "other").lower()
    suit = {
        "residential": (0.8, 0.1, 0.1),
        "commercial": (0.1, 0.9, 0.1),
        "green": (0.05, 0.05, 0.95),
    }.get(use, (0.3, 0.3, 0.3))
    return [
        use,                       # category
        _geometry_area(feature),   # area_m2
        1.5,                       # far
        suit[0],                   # s_residential
        suit[1],                   # s_commercial
        suit[2],                   # s_green
        0,                         # lock
        40.0,                      # capacity
        1.0,                       # weight
        0.0,                       # existing
        index % 4,                 # district
    ]


def _demand_attrs(index, _feature, values):
    pop = _number(values, "pop", 1.0)
    return [
        pop,                     # value
        "all",                   # category
        index,                   # zone_id
        pop * 1.5,               # production
        pop * 2.0,               # attraction
        float(index + 1),        # rank
        int(pop * 0.8),          # jobs
        index + 1,               # origin_id
        index + 1,               # dest_id
        25 + (index * 7) % 50,   # age
        0.95,                    # survival
        0.45,                    # fertility
        0.0,                     # migration
        50.0 + float((index * 5) % 40),   # score
        pop * 4.0,               # dens_ha
    ]


def _poi_attrs(index, _feature, _values):
    return [1.0, index + 1]


def _facility_attrs(index, _feature, values):
    return [index + 1, _number(values, "cap", 100.0), 1000.0, 0.0, index + 1]


def _green_attrs(_index, feature, _values):
    return [_geometry_area(feature)]


def _flows_attrs(index, _feature, values):
    length = _number(values, "length_m", 0.0)
    return [
        500.0 + float((index * 61) % 400),   # flow
        2.0 + float(index % 5) * 0.5,        # time_car
        5.0 + float(index % 7) * 1.0,        # time_transit
        length,                              # cost
    ]


# --------------------------------------------------------------------------
# Wiring decisions a name cannot make for us
# --------------------------------------------------------------------------
# Fixture roles. `_pick_layer` matches a parameter name against these before
# consulting the overrides; the order matters because the match is by substring.
ROLE_BY_PARAM = (
    ("DESTINATIONS", "pois"),
    ("ORIGINS", "demand"),
    ("RECEIVERS", "demand"),
    ("OBSERVERS", "demand"),
    ("ZONES", "demand"),
    ("DEMAND", "demand"),
    ("CANDIDATES", "facilities"),
    ("EXISTING", "facilities"),
    ("LANDMARKS", "facilities"),
    ("FACILITIES", "facilities"),
    ("BUILDINGS", "buildings"),
    ("PARCELS", "parcels"),
    ("BLOCKS", "parcels"),
    ("LANDUSE", "landuse"),
    ("GREENS", "green"),
    ("GREEN", "green"),
    ("AMENITIES", "pois"),
    ("POIS", "pois"),
    ("FLOWS", "flows"),
    ("ROADS", "network"),
    ("NETWORK_LINES", "network"),
    ("NETWORK", "network"),
    ("STUDY_AREA", "study_area"),
    ("ROI", "study_area"),
)

# Parameters whose name alone does not pick the right fixture, or whose name is
# a bare `INPUT`. Keyed (algorithm id, parameter name).
LAYER_OVERRIDES = {
    ("planx:accessequity", "INPUT"): "demand",
    ("planx:densitygrid", "INPUT"): "demand",
    ("planx:equitycrosstab", "INPUT"): "demand",
    ("planx:inequalitycurves", "INPUT"): "demand",
    ("planx:populationprojection", "INPUT"): "demand",
    ("planx:preparenetwork", "INPUT"): "network",
    ("planx:heatriskgrid", "GREEN"): "green",
    # groundmotion's EPICENTRE matches no role in ROLE_BY_PARAM, and it needs a
    # layer holding exactly one point: the study area's point-on-surface is a
    # real single epicentre at the centre of the demo city, which puts every
    # receiver a plausible distance away instead of on top of the event. The
    # tool refuses a multi-feature epicentre layer outright, so this is also
    # the case that holds that refusal honest. Its FAULT_TRACE is deliberately
    # left unset - geometry B has no fixture line, and the fault branch is
    # covered by the engine tests where a trace can be constructed directly.
    ("planx:groundmotion", "EPICENTRE"): "study_area",
    # seismicdebris takes the street centreline twice: once as a routable
    # NETWORK and once as NETWORK_LINES carrying road width.
    ("planx:seismicdebris", "NETWORK"): "network",
    ("planx:seismicdebris", "NETWORK_LINES"): "network",
    ("planx:seismicdebris", "BLOCKS"): "parcels",
    ("planx:seismicdebris", "ROI"): "study_area",
    # liquefaction's TARGET is "any geometry, one sample per feature", which no
    # role in ROLE_BY_PARAM claims. The parcels layer is the honest fit: it
    # tiles the city, so every point on its surface lands inside the DEM, and
    # it carries a real `category` column, which the same run's CATEGORY_FIELD
    # parameter then binds. That binding is not incidental - it exercises the
    # report line telling a regression-mode user that a category column is a
    # susceptibility-mode input and is being ignored, which is the only place
    # that message is produced.
    ("planx:liquefaction", "TARGET"): "parcels",
    # parkingdemand reads a land-use category and a size in the rate table's
    # own terms. The `demand` layer that ZONES would otherwise match carries a
    # constant category ("all"), which no rate row can match: every zone would
    # come back with demand 0 and the case would go green having tested
    # nothing. The parcels layer carries real varied categories
    # (residential/commercial/green/school) and a real `area_m2`, so it
    # exercises the sqm branch, the unit branch and the unmatched-category
    # report path at once. Only the sqm row is physically meaningful here: the
    # default table's residential row is per dwelling unit and this layer has
    # no dwelling count, so that row's magnitude is arithmetic, not a planning
    # figure. The case checks execution and wiring, not the totals.
    ("planx:parkingdemand", "ZONES"): "landuse",
    # parksupplybalance's SUPPLY is a parking inventory, which no role in
    # ROLE_BY_PARAM describes; the `facilities` layer carries the `capacity`
    # column it counts spaces from. ZONES is not a fixture at all here: it is
    # the demand layer the parking-demand case produced earlier in the run, so
    # this pair is a real two-step chain rather than two isolated smoke tests.
    ("planx:parkingsupplybalance", "SUPPLY"): "facilities",
}

# Enum parameters whose declared default is not the option this bundle can
# actually exercise. Keyed (algorithm id, parameter name) -> option index. The
# declared default is still the right default for a user; it is only wrong for
# a fixture set that lacks what that option demands.
ENUM_OVERRIDES = {
    # seismicdebris defaults to network source A (street / open-space
    # polygons), and the demo city emits its streets as centre lines, so the
    # polygon layer source A wants does not exist in this bundle. Handing A the
    # line fixture anyway - which is what this case used to do - makes every
    # areal output (blockage, corridors, the navigable core) come out with zero
    # area while the case still reads green. Source D cannot stand in either:
    # its ROI would be the land-use layer's own extent, which those polygons
    # tile completely, so ROI minus blocks is empty. That leaves the two
    # centreline sources, which is what B and C below are for. Source A's
    # zero-area case is a hard error now rather than an empty answer.
    ("planx:seismicdebris", "NETWORK_MODE"): 1,
    # liquefaction's TECTONIC has no default on purpose: index 0 is a sentinel
    # the tool refuses, because the active and stable-continent columns of
    # Allen & Wald Table 2 differ by over 3 logit units at the same slope and
    # choosing one silently would be choosing the answer (rule R3). The choice
    # still has to be made here, or the case exercises nothing but the refusal
    # - which is held separately in REFUSALS.
    ("planx:liquefaction", "TECTONIC"): 1,
}

# Number parameters whose declared default is not a value this bundle can run
# on. Keyed (algorithm id, parameter name) -> value. The declared default is
# still the right default for a user; it is a *sentinel* here, which is a
# different thing from a default: liquefaction's PGA_G is 0.0 meaning "not
# given", and the tool refuses a run with no shaking level rather than reading
# it as no hazard.
NUMBER_OVERRIDES = {
    ("planx:liquefaction", "PGA_G"): 0.35,
}

# A `MultipleLayers` parameter takes a list, not a single role.
MULTI_OVERRIDES = {
    "AMENITIES": ["pois", "facilities", "green"],
    "POSITIVE": ["pois", "green"],
    "NEGATIVE": ["network"],
}

# Field names in the fixture schema, by parameter name. Consulted only when the
# parameter's own declared default is empty or absent from the parent layer.
FIELD_BY_PARAM = {
    "AADT_FIELD": "aadt",
    "ACCESS_SCORE": "score",
    "AGE_FIELD": "age",
    "AREA_FIELD": "area_m2",
    "ATTRACTION_FIELD": "attraction",
    "CANDIDATE_ID": "facility_id",
    "CAPACITY_FIELD": "capacity",
    "CATEGORY_FIELD": "category",
    "COST_FIELD": "cost",
    "DEMAND_POP": "pop",
    "DEMAND_FIELD": "parking_demand",
    "DENSITY_FIELD": "dens_ha",
    "DEST_ID": "dest_id",
    "DISTRICT_FIELD": "district",
    "EMISSION_FIELD": "emission",
    "EXISTING_CAP_FIELD": "capacity",
    "EXISTING_FIELD": "existing",
    "EXISTING_ID": "facility_id",
    "FACILITY_ID": "facility_id",
    "FAR_FIELD": "far",
    "FERTILITY_FIELD": "fertility",
    "FLOOR_FIELD": "floors",
    "FLOW_FIELD": "flow",
    "FORWARD_COST": "fwd_cost",
    "GROUP_FIELD": "category",
    "GROUP_FIELD_B": "category",
    "HEAVY_FIELD": "heavy",
    "HEIGHT_FIELD": "height",
    "HIGHWAY_FIELD": "highway",
    "INFRA_FIELD": "infra",
    "JOBS_FIELD": "jobs",
    "LANES_FIELD": "lanes",
    "LEVELS_FIELD": "floors",
    "LOCK_FIELD": "lock",
    "LTS_FIELD": "lts",
    "MIGRATION_FIELD": "migration",
    "ONEWAY_FIELD": "oneway",
    "ORIGIN_ID": "origin_id",
    "POP_FIELD": "pop",
    "PRODUCTION_FIELD": "production",
    "RANK_FIELD": "rank",
    "REVERSE_COST": "rev_cost",
    "SCORE_FIELD": "score",
    "SITE_COST": "site_cost",
    "SIZE_FIELD": "area_m2",
    "SUPPLY_FIELD": "capacity",
    "SPEED_FIELD": "speed",
    "SURVIVAL_FIELD": "survival",
    "VALUE_FIELD": "value",
    "VOLUME_FIELD": "volume",
    "WEIGHT_FIELD": "weight",
    "WIDTH_FIELD": "width",
    "YEAR_FIELD": "year",
    "ZONE_ID": "zone_id",
}

# A few field parameters take several fields at once.
FIELD_LIST_OVERRIDES = {
    "SUIT_FIELDS": ["s_residential", "s_commercial", "s_green"],
}

# Rasters, by parameter name.
RASTER_BY_PARAM = (
    ("SUITABILITY", "suitability"),
    ("CONSTRAINTS", "constraints"),
    ("INUNDATION", "inundation"),
    ("RASTER_T1", "landcover_t1"),
    ("RASTER_T2", "landcover_t2"),
    ("URBAN_T1", "urban_t1"),
    ("URBAN_T2", "urban_t2"),
    ("SEED", "seed"),
    ("DEM", "dem"),
    ("DSM", "dsm"),
)

# Optional parameters deliberately left at their own default: supplying them
# would mean importing an external dataset the matrix has no business
# inventing, or pointing a tool at a directory of arbitrary third-party JSON.
SKIP_OPTIONAL = {
    "EPW",             # annualsolar: a real EnergyPlus weather file
    "FOLDER",          # scenariorank: a folder of third-party snapshot JSON
    "TARGET_CRS",      # preparenetwork: no reprojection needed, city is metric
    "CLASS_NAMES",     # landcoverchange: class labels are optional
    "BREAKS",          # equitycrosstab: quantile breaks computed internally
    "ADJACENCY",       # landallocation: optional adjacency specification
    "WEIGHTS",         # streetcomfort / scenariorank: optional weight overrides
    "OBSERVED_SHARES",
    "EXTENT",          # raster tools default to the input raster extent
    "WATER",           # no water body in the demo city
    # seismicdebris and liquefaction: no shaking raster in this bundle to
    # sample into a column. liquefaction's own PGA_FIELD is the "use a real
    # ShakeMap field" path; the constant path it falls back to is covered by
    # NUMBER_OVERRIDES, and the field path's refusals by REFUSALS.
    "PGA_FIELD",
    # groundmotion and liquefaction: the demo city has no measured site
    # velocity. liquefaction's slope-derived path is the primary run; a
    # *supplied* velocity is covered by its extra run.
    "VS30_FIELD",
    # liquefaction: _pick_raster would fall through to the DEM for this one -
    # "VS30_RASTER" matches no token in RASTER_BY_PARAM - and a terrain DSM
    # read as shear-wave velocity is a plausible-looking wrong answer rather
    # than a missing one, which is the worst kind to leave in a green sweep.
    "VS30_RASTER",
    # seismicimpact: the fixture buildings carry neither an occupancy class, a
    # population, a dwelling-unit count nor a damage-state column, and the
    # primary run reads the debris tool's own output anyway. This tool's other
    # branches have their own EXTRA_RUN entries below.
    "OCCUPANCY_FIELD",
    "POPULATION_FIELD",
    "UNITS_FIELD",
    "DAMAGE_STATE_FIELD",
    # seismicimpact: deliberately left unset so the run exercises the
    # auto-detection path rather than a hand-picked column. The chained case
    # reads the debris tool's own output, which is point centroids carrying
    # footprint_area - the field this parameter exists to find. Naming it here
    # would test the parameter and leave the detection untested, and the
    # detection is what the tool-to-tool chain actually depends on.
    "AREA_FIELD",
}

# Outputs an algorithm may legitimately decline to write even when asked, and
# why. Everything else that is requested must appear.
CONDITIONAL_OUTPUTS = {
    # Emitted only when the run finds something to connect or a path to draw.
    ("planx:nearestfacility", "SPIDER"),
    ("planx:nearestfacility", "ROUTES"),
    ("planx:odmatrix", "LINES"),
    ("planx:odroutes", "OUT_LINES"),
    ("planx:gravitymodel", "LINES"),
    ("planx:transitaccess", "OUT_DEMAND"),
}

# The main sweep runs in registration order except for these, which must run
# first because later cases consume their output as an input. Chains such as
# flowaccumulation -> handindex are exactly the interoperability a matrix of
# isolated smoke tests would miss.
# Order within this tuple is a dependency order, not an alphabetical one: a
# consumer listed before its producer has no artefact to read yet.
RUN_FIRST = (
    "planx:flowaccumulation",
    "planx:accessscore",
    "planx:densitygrid",
    "planx:landusebalance",
    "planx:facilityadequacy",
    "planx:scenariosnapshot",
    # parkingdemand -> parksupplybalance. The pair is registered in that order
    # anyway, but the consumer reads the producer's OUTPUT as its ZONES layer,
    # so the chain is declared here rather than left to depend on registration
    # order holding.
    "planx:parkingdemand",
)

# A second, differently-parameterised run of an algorithm, so that tools needing
# two comparable artefacts (compare A with B, rank several) get real files.
# algorithms id -> tuple of (artifact name, output parameter, overrides)
#
# "Differently-parameterised" has to mean a different *number*, not a different
# label. Re-running scenariosnapshot with only NAME changed handed the ranker two
# snapshots whose every metric was bit-identical, so it correctly scored nothing
# and wrote an empty detail table - a green cell that exercised the no-signal
# path and left the scoring path untested. Scenario B therefore reads a second
# access layer built at a slower speed, which is what makes the comparison tools
# compare something.
#
# The fixture city is 750 m across and a 15-minute walk at the 4.8 km/h default
# reaches 1.2 km, so at the default threshold the whole city is inside every
# origin's isochrone (hence the primary run's "full access 100.0%"). The 15-min
# default therefore cannot distinguish two scenarios of the same city; speed and
# threshold are the knobs that can, and speed moves the result hardest.
EXTRA_RUNS = {
    "planx:accessscore": (
        ("access_b", "OUTPUT", {"SPEED": 1.0}),
    ),
    "planx:scenariosnapshot": (
        ("scene_b", "OUTPUT_JSON", {"NAME": "Scenario B",
                                    "ACCESS": "art:extra/access_b"}),
    ),
    # The centerline source the primary case does not use (C sizes every road
    # from its width column; B sizes them from the OSM class table, which the
    # fixture's width column then overrides), and the multi-seed mode, which
    # the default of 0 leaves entirely unexecuted.
    "planx:seismicdebris": (
        ("network_c", "OUT_NAVIGABLE", {"NETWORK_MODE": 2}),
        ("simulated", "OUT_BUILDINGS", {"SIMULATIONS": 8}),
    ),
    # liquefaction's other two halves. The primary run is the regression model
    # on its slope-derived velocity; these are the susceptibility model - the
    # same six categories, the same four tables, reached through a completely
    # different engine path and output schema - and the regression model driven
    # by a velocity the user supplied rather than one inferred from terrain.
    "planx:liquefaction": (
        ("susceptibility", "OUTPUT", {
            "MODE": 1,
            "TARGET": "fixture:hazus_units",
            "CATEGORY_FIELD": "liq_category",
            "GROUNDWATER_M": _LIQ_GROUNDWATER_M,
        }),
        ("constant_vs30", "OUTPUT", {"VS30_MS": 320.0, "TECTONIC": 2}),
    ),
    # The casualty model's two other input paths. The primary run reads the
    # debris tool's four probability columns; these read a real occupancy
    # column against a real population column, and a single damage-state column
    # as the coarse fallback, which are the branches a user with somebody
    # else's building layer will actually hit.
    "planx:seismicimpact": (
        ("pop_field", "OUT", {
            "BUILDINGS": "fixture:buildings_occupancy",
            "OCCUPANCY_FIELD": "occupancy",
            "OCCUPANCY_SOURCE": 0,
            "POPULATION_FIELD": "population",
            "UNITS_FIELD": "units",
            "TIME_OF_DAY": 1,
        }),
        ("state_field", "OUT", {
            "BUILDINGS": "fixture:buildings_occupancy",
            "OCCUPANCY_FIELD": "occupancy",
            "DAMAGE_STATE_FIELD": "damage_state",
            "OCCUPANCY_SOURCE": 0,
            "POPULATION_FIELD": "population",
        }),
    ),
}

# Values that are neither a fixture layer nor a declared default: artefacts
# produced earlier in the run, and fixture files. A list value is joined with
# ';' for string parameters that take several paths.
VALUE_OVERRIDES = {
    ("planx:handindex", "D8_DIR"): "art:planx:flowaccumulation/OUTPUT_DIR",
    ("planx:handindex", "ACCUM"): "art:planx:flowaccumulation/OUTPUT_ACCUM",
    ("planx:scenariocompare", "SNAPSHOT_A"): "art:planx:scenariosnapshot/OUTPUT_JSON",
    ("planx:scenariocompare", "SNAPSHOT_B"): "art:extra/scene_b",
    ("planx:scenariorank", "FILES"): ["art:planx:scenariosnapshot/OUTPUT_JSON",
                                      "art:extra/scene_b"],
    # The two report tools summarise *other tools' outputs*, not raw layers:
    # report.adequacy_summary documents that facility rows carry `utilization`
    # and `status`, and that demand rows carry `covered`. Those fields exist on
    # planx:facilityadequacy's outputs and nowhere else, so pointing these at
    # the raw demo facilities would feed the summariser columns it cannot read.
    ("planx:scenariosnapshot", "ACCESS"): "art:planx:accessscore/OUTPUT",
    ("planx:scenariosnapshot", "BALANCE"): "art:planx:landusebalance/OUTPUT",
    ("planx:scenariosnapshot", "FACILITIES"): "art:planx:facilityadequacy/OUT_FACILITIES",
    ("planx:scenariosnapshot", "DEMAND"): "art:planx:facilityadequacy/OUT_DEMAND",
    ("planx:scenariosnapshot", "DENSITY"): "art:planx:densitygrid/OUTPUT",
    ("planx:performancereport", "ACCESS"): "art:planx:accessscore/OUTPUT",
    ("planx:performancereport", "BALANCE"): "art:planx:landusebalance/OUTPUT",
    ("planx:performancereport", "FACILITIES"): "art:planx:facilityadequacy/OUT_FACILITIES",
    ("planx:performancereport", "DEMAND"): "art:planx:facilityadequacy/OUT_DEMAND",
    ("planx:performancereport", "DENSITY"): "art:planx:densitygrid/OUTPUT",
    ("planx:gtfsimport", "FILE"): "fixture:gtfs",
    ("planx:transitaccess", "FILE"): "fixture:gtfs",
    ("planx:transitfrequency", "FILE"): "fixture:gtfs",
    # The balance reads the demand case's own output, so the matrix runs the
    # documented workflow end to end: area -> demand -> supply balance.
    ("planx:parkingsupplybalance", "ZONES"): "art:planx:parkingdemand/OUTPUT",
    # The casualty model's documented workflow: the debris tool's building
    # output is its input. Binding the demo buildings directly would leave the
    # chain - four damage-state probability columns, read by name and at the
    # right scale - entirely untested, and the tool would be exercised only on
    # the certainty fallback.
    ("planx:seismicimpact", "BUILDINGS"): "art:planx:seismicdebris/OUT_BUILDINGS",
}

# Timestamps the sun tools can actually compute a position for: a solstice noon.
DATETIME_OVERRIDES = {
    "WHEN": QDateTime(QDate(2026, 6, 21), QTime(12, 0)),
    "DATE": QDateTime(QDate(2026, 6, 21), QTime(12, 0)),
}


class MatrixFeedback(QgsProcessingFeedback):
    """Feedback that keeps what the algorithm said, for the report."""

    def __init__(self):
        super().__init__()
        self.info = []
        self.warnings = []

    def pushInfo(self, message):  # noqa: N802 - Qt naming
        self.info.append(str(message))

    def pushWarning(self, message):  # noqa: N802 - Qt naming
        self.warnings.append(str(message))


class CaseResult:
    """One algorithm's verdict, plus the wiring that produced it."""

    def __init__(self, algorithm_id, display_name):
        self.algorithm_id = algorithm_id
        self.display_name = display_name
        self.ok = False
        self.seconds = 0.0
        self.error = ""
        self.choices = {}
        self.outputs = {}
        self.warnings = []
        self.info = []
        # Keyed by extra-run name. An extra run is a second execution whose
        # account would otherwise be thrown away, leaving the artefact it
        # produced as the only evidence that it did anything.
        self.extra_info = {}

    def as_dict(self):
        return {
            "algorithm": self.algorithm_id,
            "display_name": self.display_name,
            "ok": self.ok,
            "seconds": round(self.seconds, 3),
            "error": self.error,
            "choices": self.choices,
            "outputs": self.outputs,
            "warnings": self.warnings,
            "info": self.info,
            "extra_info": self.extra_info,
        }


# --------------------------------------------------------------------------
# Fixture construction
# --------------------------------------------------------------------------


def _write_layer(path, name, fields, wkb_type, crs, rows, transform_context):
    """Write one GeoPackage layer from already-built (geometry, attributes)."""
    options = QgsVectorFileWriter.SaveVectorOptions()
    options.driverName = "GPKG"
    options.layerName = name
    writer = QgsVectorFileWriter.create(
        str(path), fields, wkb_type, crs, transform_context, options)
    if writer is None:
        raise RuntimeError(f"could not create a writer for {path}")
    for geometry, attributes in rows:
        feature = QgsFeature()
        feature.setGeometry(geometry)
        feature.setAttributes(attributes)
        writer.addFeature(feature)
    del writer  # flushes and closes the dataset
    if not Path(path).exists():
        raise RuntimeError(f"{path} was not written")
    return str(path)


def _augment(source, name, extra, attributes_for, out_dir, transform_context):
    """Copy ``source`` into ``out_dir`` with ``extra`` fields appended."""
    fields = QgsFields()
    for field in source.fields():
        fields.append(QgsField(field))
    for field_name, value_type in extra:
        fields.append(QgsField(field_name, value_type))

    names = [field.name().lower() for field in source.fields()]
    rows = []
    for index, feature in enumerate(source.getFeatures()):
        attributes = list(feature.attributes())
        by_name = dict(zip(names, attributes))
        rows.append((feature.geometry(),
                     attributes + attributes_for(index, feature, by_name)))
    path = Path(out_dir) / f"{name}.gpkg"
    _write_layer(path, name, fields, source.wkbType(), source.crs(), rows,
                 transform_context)
    return path


def _bounding_layer(name, extent, crs, out_dir, transform_context):
    fields = QgsFields()
    fields.append(QgsField("area_m2", DOUBLE))
    polygon = QgsGeometry.fromRect(extent)
    rows = [(polygon, [float(extent.width() * extent.height())])]
    path = Path(out_dir) / f"{name}.gpkg"
    return Path(_write_layer(path, name, fields, QgsWkbTypes.Type.Polygon, crs,
                             rows, transform_context))


def _write_gtfs(demand_layer, crs, out_path, transform_context):
    """A minimal but valid GTFS feed whose stops sit on the demo city.

    Placed on real demand points rather than at arbitrary coordinates: a feed
    thousands of kilometres away would still parse, and every transit case would
    go green while proving nothing (TRAPS 5.2).
    """
    transform = QgsCoordinateTransform(
        crs, QgsCoordinateReferenceSystem("EPSG:4326"), transform_context)

    stops = []
    for feature in demand_layer.getFeatures():
        geometry = feature.geometry()
        if geometry is None or geometry.isEmpty():
            continue
        lon_lat = transform.transform(geometry.asPoint())
        stops.append((lon_lat.x(), lon_lat.y()))
        if len(stops) == 8:
            break
    if len(stops) < 4:
        raise RuntimeError("demo city produced too few demand points for a GTFS feed")

    lines = {
        "stops.txt": "stop_id,stop_name,stop_lat,stop_lon\n" + "".join(
            f"S{i},Stop {i},{lat:.6f},{lon:.6f}\n"
            for i, (lon, lat) in enumerate(stops)),
        "routes.txt": "route_id,route_short_name,route_long_name,route_type\n"
                      "R1,1,Line 1,3\n",
        "trips.txt": "route_id,service_id,trip_id\nR1,WK,T1\n",
        "stop_times.txt": "trip_id,arrival_time,departure_time,stop_id,"
                          "stop_sequence\n" + "".join(
            f"T1,{8 + i // 12:02d}:{i * 5 % 60:02d}:00,"
            f"{8 + i // 12:02d}:{i * 5 % 60:02d}:00,S{i},{i + 1}\n"
            for i in range(len(stops))),
        "calendar.txt": "service_id,monday,tuesday,wednesday,thursday,friday,"
                        "saturday,sunday,start_date,end_date\n"
                        "WK,1,1,1,1,1,0,0,20260101,20261231\n",
    }
    with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as archive:
        for file_name, text in lines.items():
            archive.writestr(file_name, text)


def _write_raster(path, array, template):
    from osgeo import gdal

    _source, geotransform, projection = template
    rows, cols = array.shape
    driver = gdal.GetDriverByName("GTiff")
    handle = driver.Create(str(path), cols, rows, 1, gdal.GDT_Float32,
                           options=["COMPRESS=LZW"])
    handle.SetGeoTransform(geotransform)
    if projection:
        handle.SetProjection(projection)
    band = handle.GetRasterBand(1)
    band.SetNoDataValue(-9999.0)
    band.WriteArray(array)
    band.FlushCache()
    handle = None
    return str(path)


def _classify(dsm, threshold, above=1.0, below=0.0):
    import numpy as np

    out = np.where(np.isfinite(dsm), below, -9999.0)
    out[np.isfinite(dsm) & (dsm > threshold)] = above
    return out


def build_fixtures(processing, work_dir, transform_context):
    """Run ``planx:democity`` and widen its outputs into the fixture bundle."""
    import numpy as np

    from planx.algorithms._raster import read_dsm

    raw_dir = Path(work_dir) / "raw"
    raw_dir.mkdir(parents=True, exist_ok=True)

    raw = processing.run("planx:democity", {
        "SEED": CITY_SEED,
        "BLOCKS_X": CITY_BLOCKS_X,
        "BLOCKS_Y": CITY_BLOCKS_Y,
        "BLOCK_SIZE": CITY_BLOCK_SIZE,
        "CRS": CITY_CRS,
        "OUTPUT_STREETS": str(raw_dir / "streets.gpkg"),
        "OUTPUT_BUILDINGS": str(raw_dir / "buildings.gpkg"),
        "OUTPUT_LANDUSE": str(raw_dir / "landuse.gpkg"),
        "OUTPUT_POIS": str(raw_dir / "pois.gpkg"),
        "OUTPUT_FACILITIES": str(raw_dir / "facilities.gpkg"),
        "OUTPUT_DEMAND": str(raw_dir / "demand.gpkg"),
        "OUTPUT_GREEN": str(raw_dir / "green.gpkg"),
        "OUTPUT_DSM": str(raw_dir / "dsm.tif"),
    })

    def load(key):
        layer = QgsVectorLayer(str(raw[key]), key, "ogr")
        if not layer.isValid():
            raise RuntimeError(f"demo output '{key}' did not load")
        return layer

    fix_dir = Path(work_dir) / "fixtures"
    fix_dir.mkdir(parents=True, exist_ok=True)

    layers = {
        "network": _augment(load("OUTPUT_STREETS"), "network", NETWORK_EXTRA,
                            _network_attrs, fix_dir, transform_context),
        "buildings": _augment(load("OUTPUT_BUILDINGS"), "buildings",
                              BUILDINGS_EXTRA, _building_attrs, fix_dir,
                              transform_context),
        "landuse": _augment(load("OUTPUT_LANDUSE"), "landuse", LANDUSE_EXTRA,
                            _landuse_attrs, fix_dir, transform_context),
        "demand": _augment(load("OUTPUT_DEMAND"), "demand", DEMAND_EXTRA,
                           _demand_attrs, fix_dir, transform_context),
        "pois": _augment(load("OUTPUT_POIS"), "pois", POIS_EXTRA,
                         _poi_attrs, fix_dir, transform_context),
        "facilities": _augment(load("OUTPUT_FACILITIES"), "facilities",
                               FACILITIES_EXTRA, _facility_attrs, fix_dir,
                               transform_context),
        "green": _augment(load("OUTPUT_GREEN"), "green", GREEN_EXTRA,
                          _green_attrs, fix_dir, transform_context),
        "flows": _augment(load("OUTPUT_STREETS"), "flows", FLOWS_EXTRA,
                          _flows_attrs, fix_dir, transform_context),
    }
    # PARCELS is the land-use polygons again: the tools that take PARCELS want
    # an area field and per-use suitability columns, which this layer carries.
    layers["parcels"] = layers["landuse"]

    # A second copy of the buildings carrying occupancy, population, dwelling
    # units and a damage-state column. Kept separate rather than folded into
    # BUILDINGS_EXTRA: every tool that reads the buildings fixture would then
    # carry columns only the casualty model has a use for, and a renderer that
    # picks its field by name scan could start colouring by one of them.
    source = load("OUTPUT_BUILDINGS")
    layers["buildings_occupancy"] = _augment(
        source, "buildings_occupancy", BUILDINGS_EXTRA + OCCUPANCY_EXTRA,
        lambda index, feature, values: _building_attrs(index, feature, values)
        + _occupancy_attrs(index, feature, values),
        fix_dir, transform_context)

    # The land-use polygons again, carrying a liquefaction category column
    # instead of a land-use one. The susceptibility half of planx:liquefaction
    # is driven entirely by these six names, and it refuses a column of
    # anything else - an unclassified unit read as zero would report "no
    # liquefaction hazard" for a unit nobody classified. The city's own
    # `category` column holds land-use words, so covering that half of the
    # tool needs a layer that speaks the model's vocabulary.
    layers["hazus_units"] = _augment(
        load("OUTPUT_LANDUSE"), "hazus_units", (("liq_category", STRING),),
        _liq_category_attrs, fix_dir, transform_context)

    parcels = QgsVectorLayer(str(layers["landuse"]), "landuse", "ogr")
    study_area = _bounding_layer("study_area", parcels.extent(), parcels.crs(),
                                 fix_dir, transform_context)

    dsm_layer = QgsRasterLayer(str(raw["OUTPUT_DSM"]), "dsm", "gdal")
    if not dsm_layer.isValid():
        raise RuntimeError("demo DSM did not load")
    dsm, geotransform, projection, _pixel = read_dsm(dsm_layer)
    finite = dsm[np.isfinite(dsm)]
    if finite.size == 0:
        raise RuntimeError("demo DSM has no finite cells")

    template = (dsm, geotransform, projection)
    rasters = {
        # A city DSM stands in wherever a tool wants a terrain DEM. That proves
        # the plumbing, not the geomorphology: real hydrology wants real relief.
        "dsm": str(raw["OUTPUT_DSM"]),
        "dem": str(raw["OUTPUT_DSM"]),
        "inundation": _write_raster(
            fix_dir / "inundation.tif",
            _classify(dsm, float(np.percentile(finite, 25.0)), 1.0, 0.0),
            template),
        "urban_t1": _write_raster(
            fix_dir / "urban_t1.tif",
            _classify(dsm, float(np.percentile(finite, 50.0)), 1.0, 0.0),
            template),
        "urban_t2": _write_raster(
            fix_dir / "urban_t2.tif",
            _classify(dsm, float(np.percentile(finite, 40.0)), 1.0, 0.0),
            template),
        "seed": _write_raster(
            fix_dir / "seed.tif",
            _classify(dsm, float(np.percentile(finite, 75.0)), 1.0, 0.0),
            template),
        "constraints": _write_raster(
            fix_dir / "constraints.tif",
            _classify(dsm, float(np.percentile(finite, 90.0)), 1.0, 0.0),
            template),
        "suitability": _write_raster(
            fix_dir / "suitability.tif",
            np.where(np.isfinite(dsm),
                     (dsm - finite.min()) / (float(finite.max() - finite.min()) or 1.0),
                     -9999.0),
            template),
    }

    # Land-cover change needs integer class rasters, not 0/1 masks: a change
    # matrix between two two-valued rasters is trivially symmetric and would
    # pass without testing anything.
    edges = [float(np.percentile(finite, p)) for p in (0, 25, 50, 75, 100)]
    classes_t1 = np.full(dsm.shape, -9999.0)
    classes_t2 = np.full(dsm.shape, -9999.0)
    for band in range(4):
        inside = (np.isfinite(dsm) & (dsm >= edges[band])
                  & (dsm < edges[band + 1]) if band < 3
                  else np.isfinite(dsm) & (dsm >= edges[band]))
        classes_t1[inside] = band + 1
        classes_t2[inside] = min(4, band + 2)  # T2 shifts a band, so cells change
    rasters["landcover_t1"] = _write_raster(fix_dir / "landcover_t1.tif",
                                            classes_t1, template)
    rasters["landcover_t2"] = _write_raster(fix_dir / "landcover_t2.tif",
                                            classes_t2, template)

    demand_layer = QgsVectorLayer(str(layers["demand"]), "demand", "ogr")
    gtfs_path = fix_dir / "demo_gtfs.zip"
    _write_gtfs(demand_layer, parcels.crs(), gtfs_path, transform_context)

    return {
        "layers": layers,
        "study_area": study_area,
        "rasters": rasters,
        "files": {"gtfs": str(gtfs_path)},
        "raw": raw,
    }


# --------------------------------------------------------------------------
# Parameter wiring
# --------------------------------------------------------------------------


def _role(name):
    upper = name.upper()
    for token, role in ROLE_BY_PARAM:
        if token in upper:
            return role
    return None


def _pick_layer(algorithm_id, name):
    override = LAYER_OVERRIDES.get((algorithm_id, name))
    if override:
        return override, f"override:{override}"
    role = _role(name)
    if role is None:
        return None, ""
    return role, f"name:{name}->{role}"


def _pick_raster(name):
    for token, key in RASTER_BY_PARAM:
        if token in name.upper():
            return key, f"name:{name}->{key}"
    return "dsm", f"default:{name}->dsm"


def _load_tables(bundle):
    tables = {}
    for role, path in bundle["layers"].items():
        layer = QgsVectorLayer(str(path), role, "ogr")
        if not layer.isValid():
            raise RuntimeError(f"fixture '{role}' did not load from {path}")
        tables[role] = layer
    study = QgsVectorLayer(str(bundle["study_area"]), "study_area", "ogr")
    if not study.isValid():
        raise RuntimeError("study_area fixture did not load")
    tables["study_area"] = study

    rasters = {}
    for key, path in bundle["rasters"].items():
        layer = QgsRasterLayer(str(path), key, "gdal")
        if not layer.isValid():
            raise RuntimeError(f"fixture raster '{key}' did not load")
        rasters[key] = layer
    return tables, rasters


def _pick_field(name, parent_layer, parent_role):
    """A field that exists on ``parent_layer``.

    Raising is the point. A field parameter left unsupplied is reported by QGIS
    as a missing input, but a field *silently* bound to a name that is not in
    the layer makes the algorithm fall back to its own default - a green cell
    that tested nothing.
    """
    available = {field.name().lower(): field.name()
                 for field in parent_layer.fields()}

    if name in FIELD_LIST_OVERRIDES:
        wanted = FIELD_LIST_OVERRIDES[name]
        found = [available[item] for item in wanted if item in available]
        if not found:
            raise RuntimeError(
                f"'{name}' wants {wanted} on '{parent_role}', none present "
                f"(has {sorted(available)})")
        return found, f"list:{','.join(found)}"

    hint = FIELD_BY_PARAM.get(name)
    if hint and hint in available:
        return available[hint], f"hint:{hint}"
    raise RuntimeError(
        f"no fixture field for '{name}' on '{parent_role}' "
        f"(hint={hint!r}, fields={sorted(available)})")


def _destination_path(name, out_dir, algorithm_id):
    stem = f"{algorithm_id.split(':')[-1]}_{name}"
    upper = name.upper()
    if upper.endswith("HTML"):
        return str(Path(out_dir) / f"{stem}.html")
    if upper.endswith("JSON"):
        return str(Path(out_dir) / f"{stem}.json")
    return str(Path(out_dir) / f"{stem}.gpkg")


def _is_token(value):
    """True when a value names an artefact or fixture rather than a literal."""
    return value.startswith(("art:", "fixture:"))


def _resolve_special(token, artifacts, bundle):
    kind, _, key = token.partition(":")
    if kind == "art":
        if key not in artifacts:
            raise RuntimeError(f"artefact '{key}' has not been produced yet")
        return artifacts[key]
    if kind == "fixture":
        # Layers and loose files are both fixtures and they live under
        # different keys, because the layers are read back as QgsVectorLayer
        # objects elsewhere in this module. Look in both rather than make the
        # token carry the difference: 'fixture:gtfs' names a zip and
        # 'fixture:buildings_occupancy' names a layer, and a caller that
        # spelled the layer's role should not have to know which dict it
        # landed in. Every value kept in either is a path.
        for source in (bundle["files"], bundle["layers"]):
            if key in source:
                return str(source[key])
        raise RuntimeError(
            f"no fixture named '{key}' (files={sorted(bundle['files'])}, "
            f"layers={sorted(bundle['layers'])})")
    raise RuntimeError(f"unknown value token '{token}'")


def build_inputs(algorithm, bundle, tables, rasters, artifacts, out_dir, result):
    """Turn one algorithm's declared parameters into a concrete parameter dict."""
    algorithm_id = algorithm.id()
    values = {}
    for definition in algorithm.parameterDefinitions():
        name = definition.name()
        optional = _is_optional(definition)
        override = VALUE_OVERRIDES.get((algorithm_id, name))

        if definition.isDestination():
            values[name] = _destination_path(name, out_dir, algorithm_id)
            result.choices[name] = "destination"
            continue

        # An explicit decision outranks every heuristic below, whatever the
        # parameter type: many of these point a layer parameter at the artefact
        # of an earlier case, and a name-based guess would never find it.
        if override is not None:
            if isinstance(override, list):
                resolved = [_resolve_special(item, artifacts, bundle)
                            for item in override]
                values[name] = ";".join(str(item) for item in resolved)
            else:
                values[name] = _resolve_special(override, artifacts, bundle)
            result.choices[name] = f"override:{override}"
            continue

        if isinstance(definition, QgsProcessingParameterField):
            if optional and name in SKIP_OPTIONAL:
                result.choices[name] = "skipped(optional)"
                continue
            parent_role = result.choices.get(
                definition.parentLayerParameterName(), "").split("->")[-1]
            parent_role = parent_role.replace("override:", "")
            layer = tables.get(parent_role)
            if layer is None and _is_token(parent_role):
                # The parent is an artefact or fixture file rather than a
                # fixture layer. Read it back so the field is resolved against
                # the schema actually written - a field guessed onto a layer
                # that does not have it would leave the algorithm on its own
                # default and the case green having tested nothing.
                layer = QgsVectorLayer(
                    str(_resolve_special(parent_role, artifacts, bundle)),
                    parent_role, "ogr")
                if not layer.isValid():
                    raise RuntimeError(
                        f"'{name}' parent '{parent_role}' did not load")
            if layer is None:
                if optional:
                    result.choices[name] = "skipped(no parent layer)"
                    continue
                raise RuntimeError(
                    f"'{name}' needs parent "
                    f"'{definition.parentLayerParameterName()}' "
                    f"(resolved to '{parent_role}'), which is not a fixture")
            field_name, why = _pick_field(name, layer, parent_role)
            values[name] = field_name
            result.choices[name] = f"{why}@{parent_role}"
            continue

        # QgsProcessingParameterVectorLayer is a sibling of FeatureSource, not a
        # subclass, so both need the same branch.
        if isinstance(definition, (QgsProcessingParameterFeatureSource,
                                   QgsProcessingParameterVectorLayer)):
            if optional and name in SKIP_OPTIONAL:
                result.choices[name] = "skipped(optional)"
                continue
            role, why = _pick_layer(algorithm_id, name)
            if role is None:
                if optional:
                    result.choices[name] = "skipped(no fixture)"
                    continue
                raise RuntimeError(f"no fixture for required layer '{name}'")
            values[name] = tables[role]
            result.choices[name] = why
            continue

        if isinstance(definition, QgsProcessingParameterMultipleLayers):
            roles = MULTI_OVERRIDES.get(name)
            if not roles:
                if optional:
                    result.choices[name] = "skipped(no fixture)"
                    continue
                raise RuntimeError(f"no fixture list for required '{name}'")
            values[name] = [tables[role] for role in roles]
            result.choices[name] = "multi:" + ",".join(roles)
            continue

        if isinstance(definition, QgsProcessingParameterRasterLayer):
            if optional and name in SKIP_OPTIONAL:
                result.choices[name] = "skipped(optional)"
                continue
            key, why = _pick_raster(name)
            values[name] = rasters[key]
            result.choices[name] = why
            continue

        if isinstance(definition, QgsProcessingParameterNumber):
            declared = NUMBER_OVERRIDES.get((algorithm_id, name))
            if declared is not None:
                values[name] = float(declared)
                result.choices[name] = f"override:{values[name]:g}"
                continue
            default = definition.defaultValue()
            values[name] = float(default if default is not None else 0.0)
            result.choices[name] = f"default:{values[name]:g}"
            continue

        if isinstance(definition, QgsProcessingParameterBoolean):
            values[name] = bool(definition.defaultValue())
            result.choices[name] = f"default:{values[name]}"
            continue

        if isinstance(definition, QgsProcessingParameterEnum):
            chosen = ENUM_OVERRIDES.get((algorithm_id, name))
            if chosen is not None:
                values[name] = int(chosen)
                result.choices[name] = f"enum:{values[name]}"
                continue
            default = definition.defaultValue()
            values[name] = int(default if default is not None else 0)
            result.choices[name] = f"default:{values[name]}"
            continue

        if isinstance(definition, QgsProcessingParameterString):
            default = definition.defaultValue()
            if optional and default in (None, ""):
                result.choices[name] = "skipped(optional)"
                continue
            values[name] = "" if default is None else str(default)
            result.choices[name] = f"default:{values[name]!r}"
            continue

        if isinstance(definition, QgsProcessingParameterCrs):
            if optional and name in SKIP_OPTIONAL:
                result.choices[name] = "skipped(optional)"
                continue
            values[name] = QgsCoordinateReferenceSystem(CITY_CRS)
            result.choices[name] = f"crs:{CITY_CRS}"
            continue

        if isinstance(definition, QgsProcessingParameterExtent):
            result.choices[name] = "skipped(optional)"
            continue

        if isinstance(definition, QgsProcessingParameterDateTime):
            when = DATETIME_OVERRIDES.get(
                name, QDateTime(QDate(2026, 6, 21), QTime(12, 0)))
            values[name] = when
            result.choices[name] = f"datetime:{when.toString('yyyy-MM-dd HH:mm')}"
            continue

        if isinstance(definition, QgsProcessingParameterFile):
            if optional:
                result.choices[name] = "skipped(optional)"
                continue
            raise RuntimeError(f"no file fixture for '{name}'")

        # A new parameter type must fail loudly rather than be silently skipped.
        raise RuntimeError(
            f"unhandled parameter type {type(definition).__name__} for '{name}'")

    return values


# --------------------------------------------------------------------------
# Verification
# --------------------------------------------------------------------------


def _verify_vector(path_or_layer):
    layer = (path_or_layer if isinstance(path_or_layer, QgsVectorLayer)
             else QgsVectorLayer(str(path_or_layer), "matrix_out", "ogr"))
    if not layer.isValid():
        return False, f"did not load as a vector layer: {path_or_layer}"
    count = layer.featureCount()
    if count <= 0:
        return False, f"empty vector output (0 features): {path_or_layer}"
    return True, f"{count} feature(s)"


def _verify_raster(path_or_layer):
    import numpy as np
    from osgeo import gdal

    layer = (path_or_layer if isinstance(path_or_layer, QgsRasterLayer)
             else QgsRasterLayer(str(path_or_layer), "matrix_out", "gdal"))
    if not layer.isValid():
        return False, f"did not load as a raster layer: {path_or_layer}"
    handle = gdal.Open(layer.source(), gdal.GA_ReadOnly)
    if handle is None:
        return False, f"GDAL could not open {layer.source()}"
    band = handle.GetRasterBand(1)
    array = band.ReadAsArray()
    nodata = band.GetNoDataValue()
    handle = None
    if array is None or array.size == 0:
        return False, "the raster band is empty"
    good = np.isfinite(array)
    if nodata is not None:
        good &= array != nodata
    populated = int(good.sum())
    if populated == 0:
        return False, "no finite, non-nodata pixel in the raster"
    return True, f"{populated}/{array.size} populated pixel(s)"


def _verify_file(path):
    target = Path(str(path))
    if not target.exists():
        return False, f"not written: {path}"
    if target.stat().st_size <= 0:
        return False, f"empty file: {path}"
    if target.suffix.lower() == ".json":
        try:
            with target.open(encoding="utf-8") as handle:
                json.load(handle)
        except (OSError, ValueError) as exc:
            return False, f"the JSON does not parse: {exc}"
    return True, f"{target.stat().st_size} byte(s)"


# --------------------------------------------------------------------------
# Value expectations
# --------------------------------------------------------------------------
# Everything above answers "did the tool produce something?". For most tools
# that is all a smoke matrix can honestly ask. For a tool that converts units
# it is not enough: planx:groundmotion once measured every distance in the
# receivers' own metres and fed it to a model that takes kilometres, so a demo
# city 750 m across reported receivers out to 472 km - and this matrix stayed
# green, because a number wrong by 1000x is still a number in a non-empty
# layer. Entries below are checks on the *values* of the demo run, and they
# belong wherever a silent factor of a thousand is the plausible failure.

DEMO_CITY_SPAN_KM = 0.75


def _read_gpkg(path):
    """``(column names, rows as dicts, complaint)`` for a written GeoPackage.

    Read with ``sqlite3``, never with a ``QgsVectorLayer`` - and that is the
    whole point of this function. **Reading attributes** out of a written
    GeoPackage through QGIS leaves the file held open for the rest of the
    process on Windows, and an open file cannot be deleted. The extra runs
    below re-create a destination that the primary run already wrote, so a
    value check that read its output through QGIS made the *next* run of that
    algorithm die with::

        Could not create layer ...gpkg: Creation of data source failed
        (OGR error: A file system object called '...gpkg' already exists.)

    Measured on 3.44, not guessed. With no prior read, re-creating the file
    succeeds and deleting it succeeds. So does a ``featureCount()`` - which is
    why this stayed hidden: ``_verify_vector`` counts every output and those
    files stayed replaceable. Iterating the features and reading one attribute
    is what locks it, and then nothing releases it - re-creating and deleting
    both fail with ``winerror 32`` for every release strategy tried (the
    wrapper kept, ``del``-ed, and ``del``-ed plus ``gc.collect()``).

    ``sqlite3`` holds no GDAL handle: the database is opened, read and closed
    inside this call, so the file stays exactly as replaceable as it was. It
    is also the honest reading - these columns are what any other program
    would find in the file, with no QGIS interpretation in between.

    A value check must return a complaint rather than a wrong number, so
    every way of failing to read the table - unreadable file, no feature
    table, more than one, no rows - is reported here.
    """
    uri = Path(path).resolve().as_uri() + "?mode=ro"
    try:
        connection = sqlite3.connect(uri, uri=True)
    except sqlite3.Error as exc:
        return None, None, f"could not open {path} as a GeoPackage: {exc}"
    try:
        connection.row_factory = sqlite3.Row
        tables = [row[0] for row in connection.execute(
            "SELECT table_name FROM gpkg_contents WHERE data_type = 'features'"
            " ORDER BY table_name")]
        if not tables:
            return None, None, f"{path} holds no feature table"
        if len(tables) > 1:
            return None, None, (
                f"{path} holds {len(tables)} feature tables ({', '.join(tables)}), "
                f"so a column cannot be read unambiguously")
        table = tables[0]
        names = [row["name"] for row in connection.execute(
            f'PRAGMA table_info("{table}")')]
        rows = [dict(row) for row in connection.execute(f'SELECT * FROM "{table}"')]
    except sqlite3.Error as exc:
        return None, None, f"could not read {path}: {exc}"
    finally:
        connection.close()
    if not rows:
        return names, rows, f"{path} holds no row to read a value from"
    return names, rows, None


def _expect_groundmotion_distances_are_kilometres(path):
    """The demo city is under a kilometre across, so no distance may be larger.

    The epicentre is the study area's point-on-surface - the centre of a
    ~750 m square - which puts every receiver well inside a kilometre of it.
    A ceiling far above the real geometry but far below the metre-reading of
    it (472 km) separates the two without pinning a figure that the fixture
    could legitimately move.

    Note what this case is not: every receiver is in the near field, where the
    model saturates at about 0.5 g, so it exercises the site term and the row
    indexing but not the distance decay. That belongs to the engine tests.
    """
    names, rows, complaint = _read_gpkg(path)
    if complaint:
        return complaint
    if "r_km_2" in names:
        # make_fields renames a computed column that would collide with an
        # input field of the same name, so the column called r_km here would
        # be the input's, not the tool's - the same way a fixture that already
        # carried `score` made every access metric read back identical. Fail
        # loudly rather than measure the wrong column.
        return (f"the layer carries both 'r_km' and 'r_km_2', so 'r_km' is an "
                f"input field and the computed distance was renamed: {names}")
    if "r_km" not in names:
        return "no r_km column to read a distance from"
    distances = []
    for row in rows:
        value = row["r_km"]
        if value is None:
            return "an r_km value is NULL"
        distances.append(float(value))
    if not distances:
        return "no receiver to read a distance from"
    worst = max(distances)
    ceiling = 10.0 * DEMO_CITY_SPAN_KM
    if not 0.0 < worst < ceiling:
        return (f"the furthest receiver is {worst:.3f} km from the epicentre, "
                f"but the demo city is only about {DEMO_CITY_SPAN_KM:g} km "
                f"across - the distances look like the CRS's own units being "
                f"passed off as kilometres")
    return None


def _expect_impact_casualties_conserve_occupants(path):
    """Casualties must be a share of the people the scenario puts in a building.

    A casualty count is a screening number with no external reference value to
    pin - but it has a hard ceiling. Hazus rates four severities against the
    occupants present at the scenario time, so the four counts can never sum
    above the occupant count, and a run that reports more injuries than people
    is wrong whichever way the rates were read. That is exactly the class of
    defect presence-verification cannot see: the layer is full, every field is
    populated, and the numbers are physically impossible.

    The ceiling needs a floor under it to mean anything, so the run must also
    put somebody in a building. Without that, zero occupants satisfies every
    bound - see the note at the end of this function.
    """
    names, rows, complaint = _read_gpkg(path)
    if complaint:
        return complaint
    names = set(names)
    required = {"occupants", "cas_sev1", "cas_sev2", "cas_sev3", "cas_sev4",
                "cas_total", "displaced_hh", "public_shelter"}
    missing = required - names
    if missing:
        return f"missing impact column(s): {', '.join(sorted(missing))}"
    if "occupants_2" in names:
        # make_fields renames a collision, so 'occupants' below would be a
        # column of the input layer, not this tool's.
        return (f"the layer carries both 'occupants' and 'occupants_2', so the "
                f"impact columns did not land where they should: {sorted(names)}")
    seen = 0
    modelled = 0.0
    for index, row in enumerate(rows, start=1):
        value = {name: row[name] for name in required}
        if any(item is None for item in value.values()):
            return f"a NULL impact value in row {index}"
        people = float(value["occupants"])
        modelled += people
        severities = [float(value[f"cas_sev{s}"]) for s in range(1, 5)]
        total = float(value["cas_total"])
        if abs(total - sum(severities)) > 1e-6:
            return (f"row {index}: cas_total {total:.6f} is not the sum of the "
                    f"four severities {sum(severities):.6f}")
        # Outdoor casualties are counted against the same occupant pool, so
        # the four severities are bounded by the occupants whoever they are.
        if sum(severities) > people + 1e-6:
            return (f"row {index}: {sum(severities):.3f} casualties from "
                    f"{people:.3f} occupants - more people hurt than the "
                    f"building holds, so the rates or the shares were misread")
        if float(value["displaced_hh"]) > people + 1e-6:
            return (f"row {index}: {value['displaced_hh']:.3f} displaced "
                    f"households from {people:.3f} occupants")
        if float(value["public_shelter"]) > people + 1e-6:
            return (f"row {index}: {value['public_shelter']:.3f} people seeking "
                    f"shelter from {people:.3f} occupants")
        seen += 1
    if not seen:
        return "no building to read an impact value from"
    if modelled <= 0.0:
        # Every bound above is a ceiling, so a run that puts nobody in any
        # building satisfies all of them and reports a city of nobody with a
        # clean sheet. That is not a hypothetical: it is how the point-centroid
        # output of planx:seismicdebris hid a zero occupant count from this
        # check while shelter still divided a default dwelling count by it.
        return (f"the run put {modelled:.3f} people in {seen} building(s), so "
                f"every casualty and shelter number above is bounded by zero "
                f"and checks nothing")
    return None


def _expect_debris_volume_uses_the_reported_footprint(path):
    """The debris volume must be built from the area the column reports.

    ``footprint_area`` was added so the arithmetic is checkable by hand:
    material = footprint x height x the solid share of the gross volume x the
    released fraction of the damage state. If the two numbers ever come from
    different areas the identity breaks feature by feature - and nothing else
    here would notice, because the counts, the geometry and both magnitudes
    stay entirely plausible.

    That is not hypothetical: the footprint was the layer's own
    ``QgsGeometry.area()`` until v4.15.1, which is square metres only on a
    metre-unit layer with no projection scale factor. Both tools now measure
    the geometry on the ellipsoid (``planx.algorithms._units``), so this check
    also stands between the reported column and a volume converted while the
    column is not.

    Read through :func:`_read_gpkg`, not through QGIS. This is the one
    expectation whose algorithm has an extra run that re-writes the very
    destination being checked, so holding a QGIS datasource here would make
    that extra run fail on Windows - see the reasoning there.
    """
    from planx.engine import seismic

    names, rows, complaint = _read_gpkg(path)
    if complaint:
        return complaint
    required = {"footprint_area", "height_m", "debris_vol_m3", "damage_state"}
    missing = required - set(names)
    if missing:
        return f"missing debris column(s): {', '.join(sorted(missing))}"
    algorithm = QgsApplication.processingRegistry().algorithmById("planx:seismicdebris")
    if algorithm is None:
        return "planx:seismicdebris is not registered, so its solid ratio is unknown"
    declared = float(algorithm.parameterDefinition("SOLID_VOLUME_RATIO").defaultValue())
    states = {name: index for index, name in enumerate(seismic.DAMAGE_STATES)}
    ratio = None
    for index, row in enumerate(rows, start=1):
        area = float(row["footprint_area"])
        height = float(row["height_m"])
        volume = float(row["debris_vol_m3"])
        state = row["damage_state"]
        if state not in states:
            return f"row {index}: unknown damage state {state!r}"
        factor = float(seismic.material_factor([states[state]])[0])
        if factor == 0.0:
            # slight and none shed nothing that reaches the street; a non-zero
            # volume there would be a different bug, as would dividing by it.
            if volume != 0.0:
                return (f"row {index}: {volume:.6f} m3 of debris from '{state}' "
                        f"damage, which releases no material")
            continue
        if area <= 0.0 or height <= 0.0:
            return f"row {index}: {area:.3f} m2 of footprint at {height:.3f} m"
        candidate = volume / (area * height * factor)
        if ratio is None:
            ratio = candidate
        elif abs(candidate - ratio) > 1e-6 * max(1.0, abs(ratio)):
            return (f"row {index}: material volume is {candidate:.6f} of footprint x "
                    f"height x state factor where an earlier row gave {ratio:.6f}, so "
                    f"the volume and the footprint_area column are not the same area")
    if ratio is None:
        return ("no building in {0} carried both a footprint and a damage state that "
                "releases material, so the volume identity checked nothing".format(
                    path))
    if abs(ratio - declared) > 1e-6:
        return (f"the material volume is {ratio:.6f} of footprint x height x state "
                f"factor where SOLID_VOLUME_RATIO declares {declared:.6f}")
    return None


def _expect_liquefaction_matches_its_own_terms(path):
    """The reported probability must equal the model evaluated on the row's own inputs.

    The output layer carries every term the model used - PGA, Mw, CTI, Vs30 -
    so the probability is reconstructible from the same file a reader gets.
    That is the check the output counts cannot make. A column wired to the
    wrong quantity, the two models' probabilities crossed, a probability
    carried through a clip the reported inputs never went through: each of
    those produces a plausible, monotone, fully populated layer, and each of
    them fails here.

    It also holds the *order* of the clip honest. The stored CTI is the raw
    grid value, so a row whose index was clipped to the model's ceiling
    reconstructs only if the tool clipped it in the same place this does -
    before the logarithm, not after.
    """
    from planx.engine import liquefaction

    names, rows, complaint = _read_gpkg(path)
    if complaint:
        return complaint
    required = {"liq_prob", "liq_area_frac", "pga_g", "mw", "cti", "vs30_ms"}
    missing = required - set(names)
    if missing:
        return f"missing liquefaction column(s): {', '.join(sorted(missing))}"
    checked = 0
    for index, row in enumerate(rows, start=1):
        if row["liq_prob"] in (None, ""):
            continue
        expected = liquefaction.zhu_probability(
            float(row["pga_g"]), float(row["mw"]),
            float(row["cti"]), float(row["vs30_ms"]))
        if abs(float(row["liq_prob"]) - expected["probability"]) > 1e-9:
            return (f"row {index}: liq_prob is {float(row['liq_prob']):.12f} where "
                    f"the row's own PGA/Mw/CTI/Vs30 give "
                    f"{expected['probability']:.12f}")
        if abs(float(row["liq_area_frac"]) - expected["coverage"]) > 1e-9:
            return (f"row {index}: liq_area_frac is not the 0.81 coverage reading "
                    "of liq_prob")
        checked += 1
    if not checked:
        return f"no row of {path} carried a probability, so nothing was checked"
    return None


def _expect_liquefaction_matches_its_hazus_terms(path):
    """Equation 4-9, re-derived from each susceptibility row's own terms.

    The other half of the same tool, and a completely different engine path:
    no DEM, no wetness index, no Vs30. The row carries the category it was
    read as, the conditional probability of Table 4-11, both correction
    factors and the settlement, so Equation 4-9 is checkable from the file
    itself: if the identity does not close, the run applied a factor the
    columns do not show, or looked the proportion up under the wrong category.

    Equation 4-11's feet conversion is checked too, against the depth the
    extra run was pinned to. That conversion is worth a real assertion at this
    level: passing metres where the published polynomial wants feet is a
    ~7 % error that every count and every schema check passes, and it is
    exactly the class of unit defect that has shipped here before.
    """
    from planx.engine import liquefaction

    names, rows, complaint = _read_gpkg(path)
    if complaint:
        return complaint
    required = {"liq_prob", "liq_cond_prob", "liq_cat", "k_m", "k_w",
                "liq_pga_t", "liq_settle_in", "pga_g", "mw", "liq_area_frac"}
    missing = required - set(names)
    if missing:
        return f"missing liquefaction column(s): {', '.join(sorted(missing))}"
    expected_k_w = liquefaction.hazus_groundwater_factor(_LIQ_GROUNDWATER_M)
    seen = set()
    for index, row in enumerate(rows, start=1):
        category = row["liq_cat"]
        if category is None:
            return f"row {index}: no category, so the row is not a Hazus result"
        seen.add(category)
        pga = float(row["pga_g"])
        conditional = float(row["liq_cond_prob"])
        k_m = float(row["k_m"])
        k_w = float(row["k_w"])
        if abs(conditional - liquefaction.hazus_conditional(category, pga)) > 1e-9:
            return (f"row {index}: the conditional probability is not Table 4-11 "
                    f"evaluated at {pga:g} g for '{category}'")
        if abs(k_w - expected_k_w) > 1e-9:
            return (f"row {index}: K_W is {k_w:.6f} where {_LIQ_GROUNDWATER_M:g} m "
                    f"gives {expected_k_w:.6f} - Equation 4-11 takes feet")
        if abs(k_m - liquefaction.hazus_magnitude_factor(float(row["mw"]))) > 1e-9:
            return (f"row {index}: K_M is not Equation 4-10 at Mw {row['mw']}")
        proportion = liquefaction.HAZUS_PROPORTION[category]
        identity = conditional / (k_m * k_w) * proportion
        if abs(float(row["liq_prob"]) - min(max(identity, 0.0), 1.0)) > 1e-9:
            return (f"row {index}: liq_prob {float(row['liq_prob']):.12f} does not "
                    f"close Equation 4-9 on the row's own conditional, K_M, K_W "
                    f"and the Table 4-10 proportion for '{category}' "
                    f"({identity:.12f})")
        threshold = liquefaction.HAZUS_PGA_THRESHOLD.get(category)
        stored = row["liq_pga_t"]
        if (stored is None) != (threshold is None):
            return (f"row {index}: '{category}' has threshold {threshold!r} but "
                    f"the row stores {stored!r}")
        if threshold is not None and abs(float(stored) - threshold) > 1e-9:
            return (f"row {index}: threshold {stored} is not Table 4-12's "
                    f"{threshold} for '{category}'")
        if abs(float(row["liq_settle_in"])
               - float(row["liq_prob"]) * liquefaction.HAZUS_SETTLEMENT_IN[category]) > 1e-9:
            return (f"row {index}: settlement is not the probability times the "
                    f"Table 4-13 amplitude for '{category}'")
        if row["liq_area_frac"] is not None:
            return (f"row {index}: liq_area_frac is filled in susceptibility mode, "
                    "where nothing computes a coverage reading")
    if len(seen) < len(liquefaction.HAZUS_CATEGORIES):
        return (f"the run only reached {len(seen)} of the six categories "
                f"({', '.join(sorted(seen))}), so the fixture is not exercising "
                "the table it was built for")
    if not rows:
        return f"{path} holds no row, so nothing was checked"
    return None


#: Value expectations for an extra run, keyed (algorithm id, extra label).
#: An extra run exists because it takes a branch the primary case never
#: reaches, and a branch that writes the right number of rows with the wrong
#: numbers passes every count-based check there is - including the primary
#: case's own value check, which says nothing about it.
EXTRA_VALUE_EXPECTATIONS = {
    ("planx:liquefaction", "susceptibility"): {
        "OUTPUT": _expect_liquefaction_matches_its_hazus_terms,
    },
}


#: Refusals that have to be made to happen, in real QGIS, on real layers.
#: (algorithm id, overrides applied on top of that tool's resolved inputs, a
#: substring the refusal must contain). Run after the sweep so the overrides
#: only have to name what changes; everything else is the same wiring a
#: passing case used, which is what stops a refusal passing for the wrong
#: reason - a parameter that was unusable anyway would refuse too.
REFUSALS = (
    # Rule R7. Hazus assumes no ground failure when it has no input; a tool
    # that assumed the same would answer "nothing liquefies here" for a map
    # unit nobody ever classified, which is the most dangerous answer this
    # family can give. The category column is cleared rather than absent so the
    # run reaches the refusal with an otherwise valid layer.
    ("planx:liquefaction",
     {"MODE": 1, "CATEGORY_FIELD": ""},
     "Susceptibility mode needs a map-unit layer"),
)


#: algorithm id -> callable(output path) -> complaint or None. Run only when
#: the ordinary output verification passed, so a complainer here is always
#: describing a wrong value rather than a missing output.
#:
#: A check reads its output with :func:`_read_gpkg`, never with a
#: ``QgsVectorLayer``: the harness re-creates destinations in its extra runs,
#: and an open QGIS datasource on a file stops Windows from replacing it.
VALUE_EXPECTATIONS = {
    "planx:groundmotion": {
        "OUTPUT": _expect_groundmotion_distances_are_kilometres,
    },
    "planx:seismicdebris": {
        "OUT_BUILDINGS": _expect_debris_volume_uses_the_reported_footprint,
    },
    "planx:seismicimpact": {
        "OUT": _expect_impact_casualties_conserve_occupants,
    },
    "planx:liquefaction": {
        "OUTPUT": _expect_liquefaction_matches_its_own_terms,
    },
}


def check_values(algorithm_id, produced):
    """Apply this tool's value expectations. Returns a complaint, or None."""
    for output_name, expectation in VALUE_EXPECTATIONS.get(algorithm_id, {}).items():
        path = produced.get(output_name)
        if path is None:
            continue
        complaint = expectation(path)
        if complaint:
            return f"{output_name}: {complaint}"
    return None


def check_extra_values(algorithm_id, label, produced):
    """The same, for one extra run's output. Returns a complaint, or None."""
    for output_name, expectation in \
            EXTRA_VALUE_EXPECTATIONS.get((algorithm_id, label), {}).items():
        path = produced.get(output_name)
        if path is None:
            continue
        complaint = expectation(path)
        if complaint:
            return f"{output_name}: {complaint}"
    return None


def verify_outputs(algorithm, produced, result, only=None):
    ok = True
    for definition in algorithm.parameterDefinitions():
        if not definition.isDestination():
            continue
        name = definition.name()
        if only is not None and name not in only:
            continue
        if not isinstance(definition, QgsProcessingParameterFileDestination) \
                and name not in produced:
            result.outputs[name] = "not returned by processing.run"
            ok = False
            continue
        path = produced.get(name)
        if path is None:
            result.outputs[name] = "not returned by processing.run"
            ok = False
            continue
        if isinstance(definition, QgsProcessingParameterFeatureSink):
            good, detail = _verify_vector(path)
        elif isinstance(definition, QgsProcessingParameterRasterDestination):
            good, detail = _verify_raster(path)
        else:
            good, detail = _verify_file(path)
        if not good and _is_optional(definition) \
                and (algorithm.id(), name) in CONDITIONAL_OUTPUTS:
            result.outputs[name] = f"conditional, absent: {detail}"
            continue
        result.outputs[name] = detail
        if not good:
            ok = False
    return ok


# --------------------------------------------------------------------------
# Runner
# --------------------------------------------------------------------------


def _new_context(transform_context, feedback):
    context = QgsProcessingContext()
    context.setProject(QgsProject.instance())
    context.setTransformContext(transform_context)
    context.setFeedback(feedback)
    return context


def _teardown(application):
    """Shut QGIS down, except on Windows where shutting it down is the hazard.

    OSGeo4W can access-violate during teardown after a few hundred temporary
    Processing layers even when every algorithm passed, and it can also block
    for minutes. The work is finished and the report is already out by then, so
    on Windows the process is short-circuited instead (``os._exit`` in
    :func:`main`); the same guard exists in the geostats matrix for the same
    reason.
    """
    if os.name == "nt":
        return
    try:
        application.exitQgis()
    except Exception:  # noqa: BLE001 - teardown must never change the verdict
        pass


def run_matrix(only=None, verbose=False):
    from processing.core.Processing import Processing

    from planx.provider import PlanXProvider

    application = QgsApplication([], True)
    application.initQgis()
    work_dir = tempfile.mkdtemp(prefix="planx_matrix_")
    results = []
    catalog_errors = []
    try:
        Processing.initialize()
        provider = PlanXProvider()
        QgsApplication.processingRegistry().addProvider(provider)
        import processing
        transform_context = QgsProject.instance().transformContext()

        started = time.time()
        bundle = build_fixtures(processing, work_dir, transform_context)
        fixture_seconds = time.time() - started
        tables, rasters = _load_tables(bundle)

        # Keyed by the qualified Processing id, not name(): name() is the bare
        # slug the manual anchors use, and processing.run() needs the id.
        algorithms = {algorithm.id(): algorithm
                      for algorithm in provider.algorithms()}
        unqualified = sorted(key for key in algorithms if ":" not in key)
        if unqualified:
            catalog_errors.append(
                f"{len(unqualified)} algorithm id(s) are not provider-qualified: "
                f"{unqualified[:5]}")
        if len(algorithms) < MIN_EXPECTED_CASE_COUNT:
            catalog_errors.append(
                f"the provider exposes {len(algorithms)} algorithms, "
                f"expected at least {MIN_EXPECTED_CASE_COUNT}")

        order = [name for name in RUN_FIRST if name in algorithms]
        order += [name for name in sorted(algorithms) if name not in order]
        if only:
            order = [name for name in order if name in only]
        elif len(order) != len(algorithms):
            catalog_errors.append(
                f"the sweep covers {len(order)} of {len(algorithms)} "
                f"registered algorithms")

        artifacts = {}
        inputs_by_id = {}
        for algorithm_id in order:
            algorithm = algorithms[algorithm_id]
            result = CaseResult(algorithm_id, algorithm.displayName())
            out_dir = Path(work_dir) / "outputs" / algorithm_id.split(":")[-1]
            out_dir.mkdir(parents=True, exist_ok=True)
            feedback = MatrixFeedback()
            context = _new_context(transform_context, feedback)
            values = {}
            begin = time.time()
            try:
                if algorithm_id == "planx:democity":
                    # Already executed to build the fixtures. Reuse that run so
                    # the city is generated once, and still judge the real
                    # outputs of a real execution.
                    produced = bundle["raw"]
                else:
                    values = build_inputs(algorithm, bundle, tables, rasters,
                                          artifacts, out_dir, result)
                    inputs_by_id[algorithm_id] = dict(values)
                    produced = processing.run(algorithm_id, values,
                                              context=context,
                                              feedback=feedback)
                result.ok = verify_outputs(algorithm, produced, result)
                if not result.ok:
                    result.error = "one or more outputs failed verification"
                else:
                    complaint = check_values(algorithm_id, produced)
                    if complaint:
                        result.ok = False
                        result.error = f"wrong value: {complaint}"
                for definition in algorithm.parameterDefinitions():
                    if definition.isDestination() and definition.name() in produced:
                        artifacts[f"{algorithm_id}/{definition.name()}"] = \
                            produced[definition.name()]
                for artifact_name, output_name, overrides in \
                        EXTRA_RUNS.get(algorithm_id, ()):
                    extra_dir = out_dir / f"extra_{artifact_name}"
                    extra_dir.mkdir(parents=True, exist_ok=True)
                    extra = dict(values)
                    extra.update(overrides)
                    # A token, not a literal: the overrides go through the same
                    # resolver as the primary inputs, so an extra run can read an
                    # artefact an earlier extra run produced.
                    for key, value in overrides.items():
                        if isinstance(value, str) and _is_token(value):
                            extra[key] = _resolve_special(value, artifacts, bundle)
                    extra[output_name] = _destination_path(
                        output_name, extra_dir, algorithm_id)
                    extra_feedback = MatrixFeedback()
                    extra_produced = processing.run(
                        algorithm_id, extra,
                        context=_new_context(transform_context, extra_feedback),
                        feedback=extra_feedback)
                    artifacts[f"extra/{artifact_name}"] = \
                        extra_produced[output_name]
                    # Verified like the primary run. An extra run that writes
                    # an empty output tested nothing, and counting it as
                    # coverage because the primary case passed is exactly how a
                    # whole network source goes untested while looking green.
                    extra_result = CaseResult(algorithm_id,
                                              algorithm.displayName())
                    if not verify_outputs(algorithm, extra_produced,
                                          extra_result, only={output_name}):
                        result.ok = False
                        result.error = (
                            f"extra run '{artifact_name}' failed verification: "
                            f"{extra_result.outputs.get(output_name, '')}")
                    else:
                        complaint = check_extra_values(
                            algorithm_id, artifact_name, extra_produced)
                        if complaint:
                            result.ok = False
                            result.error = (
                                f"extra run '{artifact_name}' wrong value: "
                                f"{complaint}")
                    result.extra_info[artifact_name] = [
                        f"{output_name}: "
                        f"{extra_result.outputs.get(output_name, 'no output')}"
                    ] + extra_feedback.info[:20]
            except Exception as exc:  # noqa: BLE001 - the verdict is the report
                result.ok = False
                result.error = f"{type(exc).__name__}: {exc}"
                if verbose:
                    traceback.print_exc()
            result.seconds = time.time() - begin
            result.warnings = feedback.warnings[:20]
            # What the algorithm said it did. This is the evidence behind a
            # green cell that a count alone cannot give - a tool that reports
            # "Scored metrics: 0" produced a well-formed empty answer, and the
            # report should say so rather than let the output count imply more.
            result.info = feedback.info[:40]
            results.append(result)
            if verbose:
                mark = "ok  " if result.ok else "FAIL"
                print(f"  {mark} {algorithm_id:34s} {result.seconds:7.2f}s "
                      f"{result.error}", flush=True)

        # The refusals, after the sweep so they can re-use resolved inputs.
        for algorithm_id, overrides, expected in REFUSALS:
            if only and algorithm_id not in only:
                continue
            algorithm = algorithms.get(algorithm_id)
            base = inputs_by_id.get(algorithm_id)
            result = CaseResult(algorithm_id, f"{expected} (refusal)")
            result.choices = {f"refusal:{key}": str(value)
                              for key, value in overrides.items()}
            if algorithm is None or base is None:
                result.error = ("the algorithm did not run in the sweep, so its "
                                "refusal has no inputs to stand on")
                results.append(result)
                continue
            values = dict(base)
            for key, value in overrides.items():
                values[key] = value
            begin = time.time()
            try:
                processing.run(algorithm_id, values,
                               context=_new_context(transform_context,
                                                    MatrixFeedback()),
                               feedback=MatrixFeedback())
            except Exception as exc:  # noqa: BLE001 - the verdict is the report
                result.seconds = time.time() - begin
                if expected in str(exc):
                    result.ok = True
                else:
                    result.error = (f"refused, but not for the stated reason: "
                                    f"{type(exc).__name__}: {exc}")
            else:
                result.seconds = time.time() - begin
                result.error = ("the run completed where it was supposed to "
                                f"stop, so {algorithm_id} answered a question "
                                "it has no input for")
            results.append(result)
            if verbose:
                mark = "ok  " if result.ok else "FAIL"
                print(f"  {mark} {algorithm_id} refusal "
                      f"{result.seconds:7.2f}s {result.error}", flush=True)
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)
        _teardown(application)

    ok_count = sum(1 for item in results if item.ok)
    return {
        "qgis_version": Qgis.version(),
        "qgis_release": Qgis.releaseName(),
        "fixture_seconds": round(fixture_seconds, 3),
        "case_count": len(results),
        "ok_count": ok_count,
        "failed_count": len(results) - ok_count,
        "catalog_errors": catalog_errors,
        "failed": [{"algorithm": item.algorithm_id, "error": item.error,
                    "choices": item.choices, "outputs": item.outputs}
                   for item in results if not item.ok],
        "cases": [item.as_dict() for item in results],
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description="PlanX runtime algorithm matrix")
    parser.add_argument("--only", action="append",
                        help="restrict the sweep to this algorithm id "
                             "(repeatable; mainly for timing one tool)")
    parser.add_argument("--verbose", action="store_true",
                        help="print one line per case as it runs")
    parser.add_argument("--report", help="write the full JSON report here")
    args = parser.parse_args(argv)

    payload = run_matrix(only=set(args.only) if args.only else None,
                         verbose=args.verbose)
    if args.report:
        Path(args.report).write_text(
            json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    print("PLANX_RUNTIME_MATRIX_JSON=" + json.dumps(payload, sort_keys=True))
    verdict = "PASS" if (payload["failed_count"] == 0
                         and not payload["catalog_errors"]) else "FAIL"
    print(f"PLANX_RUNTIME_MATRIX: {verdict} "
          f"({payload['ok_count']}/{payload['case_count']})")
    for problem in payload["catalog_errors"]:
        print(f"  catalog: {problem}")
    sys.stdout.flush()
    # QGIS teardown on Windows can block for minutes after the work is done and
    # the report is out; the process is finished either way.
    os._exit(0 if verdict == "PASS" else 1)


if __name__ == "__main__":
    main()
