# -*- coding: utf-8 -*-
"""PlanX runtime algorithm matrix: execute every algorithm on a live runtime.

Run it with a QGIS launcher, not with a bare Python::

    C:/OSGeo4W/bin/python-qgis-ltr.bat planx/tests/qgis_runtime_algorithm_matrix.py
    C:/OSGeo4W/bin/python-qgis.bat     planx/tests/qgis_runtime_algorithm_matrix.py

Why this exists
---------------
``smoke_provider_catalog.py`` proves the *catalogue* is coherent - ids, groups,
icons, manual anchors. ``smoke_plugin.py`` loads the plugin and counts
algorithms. Neither runs an algorithm. Neither would notice a tool that raises
on every call, returns without writing its sink, or loses its outputs between
QGIS releases. "Does it load?" is not a test (TRAPS 5.1); this matrix answers
the next question a user asks: "does it run?".

What a green cell means - and what it does not
----------------------------------------------
Each case feeds one algorithm a fixture city generated by ``planx:democity``,
executes it through the Processing framework, and asserts that every declared
output was produced and carries data. A green cell therefore means: *the
algorithm was instantiated, accepted its declared parameters, ran to
completion, and emitted populated outputs on this runtime.*

A green cell does **not** prove the numbers are right. Inputs are wired from
each algorithm's own ``parameterDefinitions()`` - see :func:`_pick_layer`,
:func:`_pick_field` and :func:`_pick_raster` - rather than from 69 hand-written
per-algorithm cases, because a hand-written table silently rots when a parameter
is added. The cost of that choice is that a cell can pass while a parameter was
wired to a defensible-but-wrong fixture. Where the name is ambiguous or two
fixtures are equally plausible, the choice is pinned in ``LAYER_OVERRIDES`` /
``FIELD_BY_PARAM`` / ``RASTER_BY_PARAM``.

Numerical correctness is the job of the engine unit tests (``test_engine.py``)
and of ``smoke_plugin.py``, which checks published figures against their
sources. This matrix is the execution-and-plumbing gate. The one structural
claim it does make about values is that a vector output must contain at least
one feature and a raster output at least one finite, non-nodata pixel - so
"ran but produced nothing" is red, not green.

Every wiring decision for every parameter is recorded in the JSON the run
prints, so those claims are checkable rather than asserted.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import tempfile
import time
import traceback
import zipfile
from pathlib import Path

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
os.environ.setdefault("PYTHONUTF8", "1")

PLUGIN_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = PLUGIN_ROOT.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import qgis  # noqa: E402

# The Processing framework ships as one of QGIS's own plugins, not as an
# importable package on the launcher's default sys.path.
_QGIS_PLUGINS = Path(qgis.__file__).resolve().parent.parent / "plugins"
if _QGIS_PLUGINS.is_dir() and str(_QGIS_PLUGINS) not in sys.path:
    sys.path.insert(0, str(_QGIS_PLUGINS))

from qgis.core import (  # noqa: E402
    Qgis,
    QgsApplication,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsFeature,
    QgsField,
    QgsFields,
    QgsGeometry,
    QgsProcessingContext,
    QgsProcessingFeedback,
    QgsProcessingParameterBoolean,
    QgsProcessingParameterCrs,
    QgsProcessingParameterDateTime,
    QgsProcessingParameterDefinition,
    QgsProcessingParameterEnum,
    QgsProcessingParameterExtent,
    QgsProcessingParameterFeatureSink,
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterField,
    QgsProcessingParameterFile,
    QgsProcessingParameterFileDestination,
    QgsProcessingParameterMultipleLayers,
    QgsProcessingParameterNumber,
    QgsProcessingParameterRasterDestination,
    QgsProcessingParameterRasterLayer,
    QgsProcessingParameterString,
    QgsProcessingParameterVectorLayer,
    QgsProject,
    QgsRasterLayer,
    QgsVectorFileWriter,
    QgsVectorLayer,
    QgsWkbTypes,
)
from qgis.PyQt.QtCore import QDate, QDateTime, QTime, QVariant  # noqa: E402

# The number of algorithms this matrix is expected to cover. The catalog gate
# (smoke_provider_catalog.MIN_EXPECTED_ALGORITHM_COUNT) already guards the
# registry; this one guards that the matrix actually swept it, so a run cannot
# report a clean sweep while quietly covering fewer tools.
MIN_EXPECTED_CASE_COUNT = 70

# Fixture city. Large enough that the tools' default catchments (300-500 m) and
# service-area breaks (250/500/1000 m) land on real geometry rather than on
# empty space; small enough that the per-pixel tools stay inside a sane runtime.
CITY_CRS = "EPSG:3857"
CITY_SEED = 42
CITY_BLOCKS_X = 5
CITY_BLOCKS_Y = 5
CITY_BLOCK_SIZE = 150.0

DOUBLE = QVariant.Double
INT = QVariant.Int
STRING = QVariant.String


def _is_optional(definition) -> bool:
    """QgsProcessingParameterDefinition.FlagOptional across Qt5/Qt6 enums."""
    flags = definition.flags()
    try:
        return bool(flags & QgsProcessingParameterDefinition.Flag.FlagOptional)
    except AttributeError:
        return bool(flags & QgsProcessingParameterDefinition.FlagOptional)


# --------------------------------------------------------------------------
# Fixture schemas
# --------------------------------------------------------------------------
# The demo city ships a deliberately thin schema (a street has an id and a
# length; a building has a height). The tools under test ask for attributes the
# demo generator has no reason to invent - emissions, capacities, ages,
# suitabilities. Rather than edit the shipped generator, the matrix widens each
# fixture with the attributes the tools declare, using values that are constant
# or a simple function of the feature index. The point is that the attribute is
# present, typed and plausible; it is explicitly not a calibrated input.

NETWORK_EXTRA = (
    ("speed", DOUBLE),
    ("lanes", DOUBLE),
    ("aadt", DOUBLE),
    ("infra", STRING),
    ("lts", INT),
    ("volume", DOUBLE),
    ("emission", DOUBLE),
    ("cost", DOUBLE),
    ("score", DOUBLE),
    ("heavy", DOUBLE),
    ("oneway", INT),
    ("fwd_cost", DOUBLE),
    ("rev_cost", DOUBLE),
    ("highway", STRING),
    ("width", DOUBLE),
)

BUILDINGS_EXTRA = (("floors", INT), ("year", INT))

LANDUSE_EXTRA = (
    ("category", STRING),
    ("area_m2", DOUBLE),
    ("far", DOUBLE),
    ("s_residential", DOUBLE),
    ("s_commercial", DOUBLE),
    ("s_green", DOUBLE),
    ("lock", INT),
    ("capacity", DOUBLE),
    ("weight", DOUBLE),
    ("existing", DOUBLE),
    ("district", INT),
)

DEMAND_EXTRA = (
    ("value", DOUBLE),
    ("category", STRING),
    ("zone_id", INT),
    ("production", DOUBLE),
    ("attraction", DOUBLE),
    ("rank", DOUBLE),
    ("jobs", INT),
    ("origin_id", INT),
    ("dest_id", INT),
    ("age", INT),
    ("survival", DOUBLE),
    ("fertility", DOUBLE),
    ("migration", DOUBLE),
    ("dens_ha", DOUBLE),
    # Deliberately no `score` here. planx:accessscore computes a `score` per
    # origin, and a fixture origin layer that already carried one made
    # make_fields rename the computed column to `score_2` - so the layer the
    # report tools read kept the *input's* score under the expected name and
    # every access metric came out identical whichever origins were fed in.
    # planx:democity's own demand layer ships only `pop`, so dropping it also
    # makes the fixture faithful. The underlying fragility is real and is
    # reported to the maintainer rather than papered over here.
)

POIS_EXTRA = (("weight", DOUBLE), ("dest_id", INT))

FACILITIES_EXTRA = (
    ("facility_id", INT),
    ("capacity", DOUBLE),
    ("site_cost", DOUBLE),
    ("existing", DOUBLE),
    ("dest_id", INT),
)

GREEN_EXTRA = (("area_m2", DOUBLE),)

FLOWS_EXTRA = (
    ("flow", DOUBLE),
    ("time_car", DOUBLE),
    ("time_transit", DOUBLE),
    ("cost", DOUBLE),
)


def _geometry_area(feature):
    geometry = feature.geometry()
    if geometry is None or geometry.isEmpty():
        return 0.0
    return float(geometry.area())


def _number(values, key, fallback):
    """A demo attribute by name. By name, not by position: a GeoPackage read
    back through OGR carries its own ``fid`` field ahead of the real ones."""
    value = values.get(key)
    return fallback if value is None else float(value)


def _network_attrs(index, _feature, values):
    length = _number(values, "length_m", 0.0)
    return [
        50.0,                                  # speed
        2.0,                                   # lanes
        1200.0,                                # aadt
        "mixed",                               # infra
        1 + index % 4,                         # lts
        800.0 + float((index * 137) % 900),    # volume
        0.35,                                  # emission
        length,                                # cost
        45.0 + float((index * 7) % 50),        # score
        4.0,                                   # heavy
        0,                                     # oneway
        length,                                # fwd_cost
        length,                                # rev_cost
        "residential",                         # highway
        8.0,                                   # width
    ]


def _building_attrs(index, _feature, values):
    height = _number(values, "height", 6.0)
    return [max(1, int(round(height / 3.0))), 1975 + (index * 3) % 50]


def _landuse_attrs(index, feature, values):
    use = str(values.get("use") or "other").lower()
    suit = {
        "residential": (0.8, 0.1, 0.1),
        "commercial": (0.1, 0.9, 0.1),
        "green": (0.05, 0.05, 0.95),
    }.get(use, (0.3, 0.3, 0.3))
    return [
        use,                       # category
        _geometry_area(feature),   # area_m2
        1.5,                       # far
        suit[0],                   # s_residential
        suit[1],                   # s_commercial
        suit[2],                   # s_green
        0,                         # lock
        40.0,                      # capacity
        1.0,                       # weight
        0.0,                       # existing
        index % 4,                 # district
    ]


def _demand_attrs(index, _feature, values):
    pop = _number(values, "pop", 1.0)
    return [
        pop,                     # value
        "all",                   # category
        index,                   # zone_id
        pop * 1.5,               # production
        pop * 2.0,               # attraction
        float(index + 1),        # rank
        int(pop * 0.8),          # jobs
        index + 1,               # origin_id
        index + 1,               # dest_id
        25 + (index * 7) % 50,   # age
        0.95,                    # survival
        0.45,                    # fertility
        0.0,                     # migration
        50.0 + float((index * 5) % 40),   # score
        pop * 4.0,               # dens_ha
    ]


def _poi_attrs(index, _feature, _values):
    return [1.0, index + 1]


def _facility_attrs(index, _feature, values):
    return [index + 1, _number(values, "cap", 100.0), 1000.0, 0.0, index + 1]


def _green_attrs(_index, feature, _values):
    return [_geometry_area(feature)]


def _flows_attrs(index, _feature, values):
    length = _number(values, "length_m", 0.0)
    return [
        500.0 + float((index * 61) % 400),   # flow
        2.0 + float(index % 5) * 0.5,        # time_car
        5.0 + float(index % 7) * 1.0,        # time_transit
        length,                              # cost
    ]


# --------------------------------------------------------------------------
# Wiring decisions a name cannot make for us
# --------------------------------------------------------------------------
# Fixture roles. `_pick_layer` matches a parameter name against these before
# consulting the overrides; the order matters because the match is by substring.
ROLE_BY_PARAM = (
    ("DESTINATIONS", "pois"),
    ("ORIGINS", "demand"),
    ("RECEIVERS", "demand"),
    ("OBSERVERS", "demand"),
    ("ZONES", "demand"),
    ("DEMAND", "demand"),
    ("CANDIDATES", "facilities"),
    ("EXISTING", "facilities"),
    ("LANDMARKS", "facilities"),
    ("FACILITIES", "facilities"),
    ("BUILDINGS", "buildings"),
    ("PARCELS", "parcels"),
    ("BLOCKS", "parcels"),
    ("LANDUSE", "landuse"),
    ("GREENS", "green"),
    ("GREEN", "green"),
    ("AMENITIES", "pois"),
    ("POIS", "pois"),
    ("FLOWS", "flows"),
    ("ROADS", "network"),
    ("NETWORK_LINES", "network"),
    ("NETWORK", "network"),
    ("STUDY_AREA", "study_area"),
    ("ROI", "study_area"),
)

# Parameters whose name alone does not pick the right fixture, or whose name is
# a bare `INPUT`. Keyed (algorithm id, parameter name).
LAYER_OVERRIDES = {
    ("planx:accessequity", "INPUT"): "demand",
    ("planx:densitygrid", "INPUT"): "demand",
    ("planx:equitycrosstab", "INPUT"): "demand",
    ("planx:inequalitycurves", "INPUT"): "demand",
    ("planx:populationprojection", "INPUT"): "demand",
    ("planx:preparenetwork", "INPUT"): "network",
    ("planx:heatriskgrid", "GREEN"): "green",
    # seismicdebris takes the street centreline twice: once as a routable
    # NETWORK and once as NETWORK_LINES carrying road width.
    ("planx:seismicdebris", "NETWORK"): "network",
    ("planx:seismicdebris", "NETWORK_LINES"): "network",
    ("planx:seismicdebris", "BLOCKS"): "parcels",
    ("planx:seismicdebris", "ROI"): "study_area",
    # parkingdemand reads a land-use category and a size in the rate table's
    # own terms. The `demand` layer that ZONES would otherwise match carries a
    # constant category ("all"), which no rate row can match: every zone would
    # come back with demand 0 and the case would go green having tested
    # nothing. The parcels layer carries real varied categories
    # (residential/commercial/green/school) and a real `area_m2`, so it
    # exercises the sqm branch, the unit branch and the unmatched-category
    # report path at once. Only the sqm row is physically meaningful here: the
    # default table's residential row is per dwelling unit and this layer has
    # no dwelling count, so that row's magnitude is arithmetic, not a planning
    # figure. The case checks execution and wiring, not the totals.
    ("planx:parkingdemand", "ZONES"): "landuse",
}

# A `MultipleLayers` parameter takes a list, not a single role.
MULTI_OVERRIDES = {
    "AMENITIES": ["pois", "facilities", "green"],
    "POSITIVE": ["pois", "green"],
    "NEGATIVE": ["network"],
}

# Field names in the fixture schema, by parameter name. Consulted only when the
# parameter's own declared default is empty or absent from the parent layer.
FIELD_BY_PARAM = {
    "AADT_FIELD": "aadt",
    "ACCESS_SCORE": "score",
    "AGE_FIELD": "age",
    "AREA_FIELD": "area_m2",
    "ATTRACTION_FIELD": "attraction",
    "CANDIDATE_ID": "facility_id",
    "CAPACITY_FIELD": "capacity",
    "CATEGORY_FIELD": "category",
    "COST_FIELD": "cost",
    "DEMAND_POP": "pop",
    "DENSITY_FIELD": "dens_ha",
    "DEST_ID": "dest_id",
    "DISTRICT_FIELD": "district",
    "EMISSION_FIELD": "emission",
    "EXISTING_CAP_FIELD": "capacity",
    "EXISTING_FIELD": "existing",
    "EXISTING_ID": "facility_id",
    "FACILITY_ID": "facility_id",
    "FAR_FIELD": "far",
    "FERTILITY_FIELD": "fertility",
    "FLOOR_FIELD": "floors",
    "FLOW_FIELD": "flow",
    "FORWARD_COST": "fwd_cost",
    "GROUP_FIELD": "category",
    "GROUP_FIELD_B": "category",
    "HEAVY_FIELD": "heavy",
    "HEIGHT_FIELD": "height",
    "HIGHWAY_FIELD": "highway",
    "INFRA_FIELD": "infra",
    "JOBS_FIELD": "jobs",
    "LANES_FIELD": "lanes",
    "LEVELS_FIELD": "floors",
    "LOCK_FIELD": "lock",
    "LTS_FIELD": "lts",
    "MIGRATION_FIELD": "migration",
    "ONEWAY_FIELD": "oneway",
    "ORIGIN_ID": "origin_id",
    "POP_FIELD": "pop",
    "PRODUCTION_FIELD": "production",
    "RANK_FIELD": "rank",
    "REVERSE_COST": "rev_cost",
    "SCORE_FIELD": "score",
    "SITE_COST": "site_cost",
    "SIZE_FIELD": "area_m2",
    "SPEED_FIELD": "speed",
    "SURVIVAL_FIELD": "survival",
    "VALUE_FIELD": "value",
    "VOLUME_FIELD": "volume",
    "WEIGHT_FIELD": "weight",
    "WIDTH_FIELD": "width",
    "YEAR_FIELD": "year",
    "ZONE_ID": "zone_id",
}

# A few field parameters take several fields at once.
FIELD_LIST_OVERRIDES = {
    "SUIT_FIELDS": ["s_residential", "s_commercial", "s_green"],
}

# Rasters, by parameter name.
RASTER_BY_PARAM = (
    ("SUITABILITY", "suitability"),
    ("CONSTRAINTS", "constraints"),
    ("INUNDATION", "inundation"),
    ("RASTER_T1", "landcover_t1"),
    ("RASTER_T2", "landcover_t2"),
    ("URBAN_T1", "urban_t1"),
    ("URBAN_T2", "urban_t2"),
    ("SEED", "seed"),
    ("DEM", "dem"),
    ("DSM", "dsm"),
)

# Optional parameters deliberately left at their own default: supplying them
# would mean importing an external dataset the matrix has no business
# inventing, or pointing a tool at a directory of arbitrary third-party JSON.
SKIP_OPTIONAL = {
    "EPW",             # annualsolar: a real EnergyPlus weather file
    "FOLDER",          # scenariorank: a folder of third-party snapshot JSON
    "TARGET_CRS",      # preparenetwork: no reprojection needed, city is metric
    "CLASS_NAMES",     # landcoverchange: class labels are optional
    "BREAKS",          # equitycrosstab: quantile breaks computed internally
    "ADJACENCY",       # landallocation: optional adjacency specification
    "WEIGHTS",         # streetcomfort / scenariorank: optional weight overrides
    "OBSERVED_SHARES",
    "EXTENT",          # raster tools default to the input raster extent
    "WATER",           # no water body in the demo city
}

# Outputs an algorithm may legitimately decline to write even when asked, and
# why. Everything else that is requested must appear.
CONDITIONAL_OUTPUTS = {
    # Emitted only when the run finds something to connect or a path to draw.
    ("planx:nearestfacility", "SPIDER"),
    ("planx:nearestfacility", "ROUTES"),
    ("planx:odmatrix", "LINES"),
    ("planx:odroutes", "OUT_LINES"),
    ("planx:gravitymodel", "LINES"),
    ("planx:transitaccess", "OUT_DEMAND"),
}

# The main sweep runs in registration order except for these, which must run
# first because later cases consume their output as an input. Chains such as
# flowaccumulation -> handindex are exactly the interoperability a matrix of
# isolated smoke tests would miss.
# Order within this tuple is a dependency order, not an alphabetical one: a
# consumer listed before its producer has no artefact to read yet.
RUN_FIRST = (
    "planx:flowaccumulation",
    "planx:accessscore",
    "planx:densitygrid",
    "planx:landusebalance",
    "planx:facilityadequacy",
    "planx:scenariosnapshot",
)

# A second, differently-parameterised run of an algorithm, so that tools needing
# two comparable artefacts (compare A with B, rank several) get real files.
# algorithms id -> tuple of (artifact name, output parameter, overrides)
#
# "Differently-parameterised" has to mean a different *number*, not a different
# label. Re-running scenariosnapshot with only NAME changed handed the ranker two
# snapshots whose every metric was bit-identical, so it correctly scored nothing
# and wrote an empty detail table - a green cell that exercised the no-signal
# path and left the scoring path untested. Scenario B therefore reads a second
# access layer built at a slower speed, which is what makes the comparison tools
# compare something.
#
# The fixture city is 750 m across and a 15-minute walk at the 4.8 km/h default
# reaches 1.2 km, so at the default threshold the whole city is inside every
# origin's isochrone (hence the primary run's "full access 100.0%"). The 15-min
# default therefore cannot distinguish two scenarios of the same city; speed and
# threshold are the knobs that can, and speed moves the result hardest.
EXTRA_RUNS = {
    "planx:accessscore": (
        ("access_b", "OUTPUT", {"SPEED": 1.0}),
    ),
    "planx:scenariosnapshot": (
        ("scene_b", "OUTPUT_JSON", {"NAME": "Scenario B",
                                    "ACCESS": "art:extra/access_b"}),
    ),
}

# Values that are neither a fixture layer nor a declared default: artefacts
# produced earlier in the run, and fixture files. A list value is joined with
# ';' for string parameters that take several paths.
VALUE_OVERRIDES = {
    ("planx:handindex", "D8_DIR"): "art:planx:flowaccumulation/OUTPUT_DIR",
    ("planx:handindex", "ACCUM"): "art:planx:flowaccumulation/OUTPUT_ACCUM",
    ("planx:scenariocompare", "SNAPSHOT_A"): "art:planx:scenariosnapshot/OUTPUT_JSON",
    ("planx:scenariocompare", "SNAPSHOT_B"): "art:extra/scene_b",
    ("planx:scenariorank", "FILES"): ["art:planx:scenariosnapshot/OUTPUT_JSON",
                                      "art:extra/scene_b"],
    # The two report tools summarise *other tools' outputs*, not raw layers:
    # report.adequacy_summary documents that facility rows carry `utilization`
    # and `status`, and that demand rows carry `covered`. Those fields exist on
    # planx:facilityadequacy's outputs and nowhere else, so pointing these at
    # the raw demo facilities would feed the summariser columns it cannot read.
    ("planx:scenariosnapshot", "ACCESS"): "art:planx:accessscore/OUTPUT",
    ("planx:scenariosnapshot", "BALANCE"): "art:planx:landusebalance/OUTPUT",
    ("planx:scenariosnapshot", "FACILITIES"): "art:planx:facilityadequacy/OUT_FACILITIES",
    ("planx:scenariosnapshot", "DEMAND"): "art:planx:facilityadequacy/OUT_DEMAND",
    ("planx:scenariosnapshot", "DENSITY"): "art:planx:densitygrid/OUTPUT",
    ("planx:performancereport", "ACCESS"): "art:planx:accessscore/OUTPUT",
    ("planx:performancereport", "BALANCE"): "art:planx:landusebalance/OUTPUT",
    ("planx:performancereport", "FACILITIES"): "art:planx:facilityadequacy/OUT_FACILITIES",
    ("planx:performancereport", "DEMAND"): "art:planx:facilityadequacy/OUT_DEMAND",
    ("planx:performancereport", "DENSITY"): "art:planx:densitygrid/OUTPUT",
    ("planx:gtfsimport", "FILE"): "fixture:gtfs",
    ("planx:transitaccess", "FILE"): "fixture:gtfs",
    ("planx:transitfrequency", "FILE"): "fixture:gtfs",
}

# Timestamps the sun tools can actually compute a position for: a solstice noon.
DATETIME_OVERRIDES = {
    "WHEN": QDateTime(QDate(2026, 6, 21), QTime(12, 0)),
    "DATE": QDateTime(QDate(2026, 6, 21), QTime(12, 0)),
}


class MatrixFeedback(QgsProcessingFeedback):
    """Feedback that keeps what the algorithm said, for the report."""

    def __init__(self):
        super().__init__()
        self.info = []
        self.warnings = []

    def pushInfo(self, message):  # noqa: N802 - Qt naming
        self.info.append(str(message))

    def pushWarning(self, message):  # noqa: N802 - Qt naming
        self.warnings.append(str(message))


class CaseResult:
    """One algorithm's verdict, plus the wiring that produced it."""

    def __init__(self, algorithm_id, display_name):
        self.algorithm_id = algorithm_id
        self.display_name = display_name
        self.ok = False
        self.seconds = 0.0
        self.error = ""
        self.choices = {}
        self.outputs = {}
        self.warnings = []
        self.info = []
        # Keyed by extra-run name. An extra run is a second execution whose
        # account would otherwise be thrown away, leaving the artefact it
        # produced as the only evidence that it did anything.
        self.extra_info = {}

    def as_dict(self):
        return {
            "algorithm": self.algorithm_id,
            "display_name": self.display_name,
            "ok": self.ok,
            "seconds": round(self.seconds, 3),
            "error": self.error,
            "choices": self.choices,
            "outputs": self.outputs,
            "warnings": self.warnings,
            "info": self.info,
            "extra_info": self.extra_info,
        }


# --------------------------------------------------------------------------
# Fixture construction
# --------------------------------------------------------------------------


def _write_layer(path, name, fields, wkb_type, crs, rows, transform_context):
    """Write one GeoPackage layer from already-built (geometry, attributes)."""
    options = QgsVectorFileWriter.SaveVectorOptions()
    options.driverName = "GPKG"
    options.layerName = name
    writer = QgsVectorFileWriter.create(
        str(path), fields, wkb_type, crs, transform_context, options)
    if writer is None:
        raise RuntimeError(f"could not create a writer for {path}")
    for geometry, attributes in rows:
        feature = QgsFeature()
        feature.setGeometry(geometry)
        feature.setAttributes(attributes)
        writer.addFeature(feature)
    del writer  # flushes and closes the dataset
    if not Path(path).exists():
        raise RuntimeError(f"{path} was not written")
    return str(path)


def _augment(source, name, extra, attributes_for, out_dir, transform_context):
    """Copy ``source`` into ``out_dir`` with ``extra`` fields appended."""
    fields = QgsFields()
    for field in source.fields():
        fields.append(QgsField(field))
    for field_name, value_type in extra:
        fields.append(QgsField(field_name, value_type))

    names = [field.name().lower() for field in source.fields()]
    rows = []
    for index, feature in enumerate(source.getFeatures()):
        attributes = list(feature.attributes())
        by_name = dict(zip(names, attributes))
        rows.append((feature.geometry(),
                     attributes + attributes_for(index, feature, by_name)))
    path = Path(out_dir) / f"{name}.gpkg"
    _write_layer(path, name, fields, source.wkbType(), source.crs(), rows,
                 transform_context)
    return path


def _bounding_layer(name, extent, crs, out_dir, transform_context):
    fields = QgsFields()
    fields.append(QgsField("area_m2", DOUBLE))
    polygon = QgsGeometry.fromRect(extent)
    rows = [(polygon, [float(extent.width() * extent.height())])]
    path = Path(out_dir) / f"{name}.gpkg"
    return Path(_write_layer(path, name, fields, QgsWkbTypes.Type.Polygon, crs,
                             rows, transform_context))


def _write_gtfs(demand_layer, crs, out_path, transform_context):
    """A minimal but valid GTFS feed whose stops sit on the demo city.

    Placed on real demand points rather than at arbitrary coordinates: a feed
    thousands of kilometres away would still parse, and every transit case would
    go green while proving nothing (TRAPS 5.2).
    """
    transform = QgsCoordinateTransform(
        crs, QgsCoordinateReferenceSystem("EPSG:4326"), transform_context)

    stops = []
    for feature in demand_layer.getFeatures():
        geometry = feature.geometry()
        if geometry is None or geometry.isEmpty():
            continue
        lon_lat = transform.transform(geometry.asPoint())
        stops.append((lon_lat.x(), lon_lat.y()))
        if len(stops) == 8:
            break
    if len(stops) < 4:
        raise RuntimeError("demo city produced too few demand points for a GTFS feed")

    lines = {
        "stops.txt": "stop_id,stop_name,stop_lat,stop_lon\n" + "".join(
            f"S{i},Stop {i},{lat:.6f},{lon:.6f}\n"
            for i, (lon, lat) in enumerate(stops)),
        "routes.txt": "route_id,route_short_name,route_long_name,route_type\n"
                      "R1,1,Line 1,3\n",
        "trips.txt": "route_id,service_id,trip_id\nR1,WK,T1\n",
        "stop_times.txt": "trip_id,arrival_time,departure_time,stop_id,"
                          "stop_sequence\n" + "".join(
            f"T1,{8 + i // 12:02d}:{i * 5 % 60:02d}:00,"
            f"{8 + i // 12:02d}:{i * 5 % 60:02d}:00,S{i},{i + 1}\n"
            for i in range(len(stops))),
        "calendar.txt": "service_id,monday,tuesday,wednesday,thursday,friday,"
                        "saturday,sunday,start_date,end_date\n"
                        "WK,1,1,1,1,1,0,0,20260101,20261231\n",
    }
    with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as archive:
        for file_name, text in lines.items():
            archive.writestr(file_name, text)


def _write_raster(path, array, template):
    from osgeo import gdal

    _source, geotransform, projection = template
    rows, cols = array.shape
    driver = gdal.GetDriverByName("GTiff")
    handle = driver.Create(str(path), cols, rows, 1, gdal.GDT_Float32,
                           options=["COMPRESS=LZW"])
    handle.SetGeoTransform(geotransform)
    if projection:
        handle.SetProjection(projection)
    band = handle.GetRasterBand(1)
    band.SetNoDataValue(-9999.0)
    band.WriteArray(array)
    band.FlushCache()
    handle = None
    return str(path)


def _classify(dsm, threshold, above=1.0, below=0.0):
    import numpy as np

    out = np.where(np.isfinite(dsm), below, -9999.0)
    out[np.isfinite(dsm) & (dsm > threshold)] = above
    return out


def build_fixtures(processing, work_dir, transform_context):
    """Run ``planx:democity`` and widen its outputs into the fixture bundle."""
    import numpy as np

    from planx.algorithms._raster import read_dsm

    raw_dir = Path(work_dir) / "raw"
    raw_dir.mkdir(parents=True, exist_ok=True)

    raw = processing.run("planx:democity", {
        "SEED": CITY_SEED,
        "BLOCKS_X": CITY_BLOCKS_X,
        "BLOCKS_Y": CITY_BLOCKS_Y,
        "BLOCK_SIZE": CITY_BLOCK_SIZE,
        "CRS": CITY_CRS,
        "OUTPUT_STREETS": str(raw_dir / "streets.gpkg"),
        "OUTPUT_BUILDINGS": str(raw_dir / "buildings.gpkg"),
        "OUTPUT_LANDUSE": str(raw_dir / "landuse.gpkg"),
        "OUTPUT_POIS": str(raw_dir / "pois.gpkg"),
        "OUTPUT_FACILITIES": str(raw_dir / "facilities.gpkg"),
        "OUTPUT_DEMAND": str(raw_dir / "demand.gpkg"),
        "OUTPUT_GREEN": str(raw_dir / "green.gpkg"),
        "OUTPUT_DSM": str(raw_dir / "dsm.tif"),
    })

    def load(key):
        layer = QgsVectorLayer(str(raw[key]), key, "ogr")
        if not layer.isValid():
            raise RuntimeError(f"demo output '{key}' did not load")
        return layer

    fix_dir = Path(work_dir) / "fixtures"
    fix_dir.mkdir(parents=True, exist_ok=True)

    layers = {
        "network": _augment(load("OUTPUT_STREETS"), "network", NETWORK_EXTRA,
                            _network_attrs, fix_dir, transform_context),
        "buildings": _augment(load("OUTPUT_BUILDINGS"), "buildings",
                              BUILDINGS_EXTRA, _building_attrs, fix_dir,
                              transform_context),
        "landuse": _augment(load("OUTPUT_LANDUSE"), "landuse", LANDUSE_EXTRA,
                            _landuse_attrs, fix_dir, transform_context),
        "demand": _augment(load("OUTPUT_DEMAND"), "demand", DEMAND_EXTRA,
                           _demand_attrs, fix_dir, transform_context),
        "pois": _augment(load("OUTPUT_POIS"), "pois", POIS_EXTRA,
                         _poi_attrs, fix_dir, transform_context),
        "facilities": _augment(load("OUTPUT_FACILITIES"), "facilities",
                               FACILITIES_EXTRA, _facility_attrs, fix_dir,
                               transform_context),
        "green": _augment(load("OUTPUT_GREEN"), "green", GREEN_EXTRA,
                          _green_attrs, fix_dir, transform_context),
        "flows": _augment(load("OUTPUT_STREETS"), "flows", FLOWS_EXTRA,
                          _flows_attrs, fix_dir, transform_context),
    }
    # PARCELS is the land-use polygons again: the tools that take PARCELS want
    # an area field and per-use suitability columns, which this layer carries.
    layers["parcels"] = layers["landuse"]

    parcels = QgsVectorLayer(str(layers["landuse"]), "landuse", "ogr")
    study_area = _bounding_layer("study_area", parcels.extent(), parcels.crs(),
                                 fix_dir, transform_context)

    dsm_layer = QgsRasterLayer(str(raw["OUTPUT_DSM"]), "dsm", "gdal")
    if not dsm_layer.isValid():
        raise RuntimeError("demo DSM did not load")
    dsm, geotransform, projection, _pixel = read_dsm(dsm_layer)
    finite = dsm[np.isfinite(dsm)]
    if finite.size == 0:
        raise RuntimeError("demo DSM has no finite cells")

    template = (dsm, geotransform, projection)
    rasters = {
        # A city DSM stands in wherever a tool wants a terrain DEM. That proves
        # the plumbing, not the geomorphology: real hydrology wants real relief.
        "dsm": str(raw["OUTPUT_DSM"]),
        "dem": str(raw["OUTPUT_DSM"]),
        "inundation": _write_raster(
            fix_dir / "inundation.tif",
            _classify(dsm, float(np.percentile(finite, 25.0)), 1.0, 0.0),
            template),
        "urban_t1": _write_raster(
            fix_dir / "urban_t1.tif",
            _classify(dsm, float(np.percentile(finite, 50.0)), 1.0, 0.0),
            template),
        "urban_t2": _write_raster(
            fix_dir / "urban_t2.tif",
            _classify(dsm, float(np.percentile(finite, 40.0)), 1.0, 0.0),
            template),
        "seed": _write_raster(
            fix_dir / "seed.tif",
            _classify(dsm, float(np.percentile(finite, 75.0)), 1.0, 0.0),
            template),
        "constraints": _write_raster(
            fix_dir / "constraints.tif",
            _classify(dsm, float(np.percentile(finite, 90.0)), 1.0, 0.0),
            template),
        "suitability": _write_raster(
            fix_dir / "suitability.tif",
            np.where(np.isfinite(dsm),
                     (dsm - finite.min()) / (float(finite.max() - finite.min()) or 1.0),
                     -9999.0),
            template),
    }

    # Land-cover change needs integer class rasters, not 0/1 masks: a change
    # matrix between two two-valued rasters is trivially symmetric and would
    # pass without testing anything.
    edges = [float(np.percentile(finite, p)) for p in (0, 25, 50, 75, 100)]
    classes_t1 = np.full(dsm.shape, -9999.0)
    classes_t2 = np.full(dsm.shape, -9999.0)
    for band in range(4):
        inside = (np.isfinite(dsm) & (dsm >= edges[band])
                  & (dsm < edges[band + 1]) if band < 3
                  else np.isfinite(dsm) & (dsm >= edges[band]))
        classes_t1[inside] = band + 1
        classes_t2[inside] = min(4, band + 2)  # T2 shifts a band, so cells change
    rasters["landcover_t1"] = _write_raster(fix_dir / "landcover_t1.tif",
                                            classes_t1, template)
    rasters["landcover_t2"] = _write_raster(fix_dir / "landcover_t2.tif",
                                            classes_t2, template)

    demand_layer = QgsVectorLayer(str(layers["demand"]), "demand", "ogr")
    gtfs_path = fix_dir / "demo_gtfs.zip"
    _write_gtfs(demand_layer, parcels.crs(), gtfs_path, transform_context)

    return {
        "layers": layers,
        "study_area": study_area,
        "rasters": rasters,
        "files": {"gtfs": str(gtfs_path)},
        "raw": raw,
    }


# --------------------------------------------------------------------------
# Parameter wiring
# --------------------------------------------------------------------------


def _role(name):
    upper = name.upper()
    for token, role in ROLE_BY_PARAM:
        if token in upper:
            return role
    return None


def _pick_layer(algorithm_id, name):
    override = LAYER_OVERRIDES.get((algorithm_id, name))
    if override:
        return override, f"override:{override}"
    role = _role(name)
    if role is None:
        return None, ""
    return role, f"name:{name}->{role}"


def _pick_raster(name):
    for token, key in RASTER_BY_PARAM:
        if token in name.upper():
            return key, f"name:{name}->{key}"
    return "dsm", f"default:{name}->dsm"


def _load_tables(bundle):
    tables = {}
    for role, path in bundle["layers"].items():
        layer = QgsVectorLayer(str(path), role, "ogr")
        if not layer.isValid():
            raise RuntimeError(f"fixture '{role}' did not load from {path}")
        tables[role] = layer
    study = QgsVectorLayer(str(bundle["study_area"]), "study_area", "ogr")
    if not study.isValid():
        raise RuntimeError("study_area fixture did not load")
    tables["study_area"] = study

    rasters = {}
    for key, path in bundle["rasters"].items():
        layer = QgsRasterLayer(str(path), key, "gdal")
        if not layer.isValid():
            raise RuntimeError(f"fixture raster '{key}' did not load")
        rasters[key] = layer
    return tables, rasters


def _pick_field(name, parent_layer, parent_role):
    """A field that exists on ``parent_layer``.

    Raising is the point. A field parameter left unsupplied is reported by QGIS
    as a missing input, but a field *silently* bound to a name that is not in
    the layer makes the algorithm fall back to its own default - a green cell
    that tested nothing.
    """
    available = {field.name().lower(): field.name()
                 for field in parent_layer.fields()}

    if name in FIELD_LIST_OVERRIDES:
        wanted = FIELD_LIST_OVERRIDES[name]
        found = [available[item] for item in wanted if item in available]
        if not found:
            raise RuntimeError(
                f"'{name}' wants {wanted} on '{parent_role}', none present "
                f"(has {sorted(available)})")
        return found, f"list:{','.join(found)}"

    hint = FIELD_BY_PARAM.get(name)
    if hint and hint in available:
        return available[hint], f"hint:{hint}"
    raise RuntimeError(
        f"no fixture field for '{name}' on '{parent_role}' "
        f"(hint={hint!r}, fields={sorted(available)})")


def _destination_path(name, out_dir, algorithm_id):
    stem = f"{algorithm_id.split(':')[-1]}_{name}"
    upper = name.upper()
    if upper.endswith("HTML"):
        return str(Path(out_dir) / f"{stem}.html")
    if upper.endswith("JSON"):
        return str(Path(out_dir) / f"{stem}.json")
    return str(Path(out_dir) / f"{stem}.gpkg")


def _is_token(value):
    """True when a value names an artefact or fixture rather than a literal."""
    return value.startswith(("art:", "fixture:"))


def _resolve_special(token, artifacts, bundle):
    kind, _, key = token.partition(":")
    if kind == "art":
        if key not in artifacts:
            raise RuntimeError(f"artefact '{key}' has not been produced yet")
        return artifacts[key]
    if kind == "fixture":
        return bundle["files"][key]
    raise RuntimeError(f"unknown value token '{token}'")


def build_inputs(algorithm, bundle, tables, rasters, artifacts, out_dir, result):
    """Turn one algorithm's declared parameters into a concrete parameter dict."""
    algorithm_id = algorithm.id()
    values = {}
    for definition in algorithm.parameterDefinitions():
        name = definition.name()
        optional = _is_optional(definition)
        override = VALUE_OVERRIDES.get((algorithm_id, name))

        if definition.isDestination():
            values[name] = _destination_path(name, out_dir, algorithm_id)
            result.choices[name] = "destination"
            continue

        # An explicit decision outranks every heuristic below, whatever the
        # parameter type: many of these point a layer parameter at the artefact
        # of an earlier case, and a name-based guess would never find it.
        if override is not None:
            if isinstance(override, list):
                resolved = [_resolve_special(item, artifacts, bundle)
                            for item in override]
                values[name] = ";".join(str(item) for item in resolved)
            else:
                values[name] = _resolve_special(override, artifacts, bundle)
            result.choices[name] = f"override:{override}"
            continue

        if isinstance(definition, QgsProcessingParameterField):
            if optional and name in SKIP_OPTIONAL:
                result.choices[name] = "skipped(optional)"
                continue
            parent_role = result.choices.get(
                definition.parentLayerParameterName(), "").split("->")[-1]
            parent_role = parent_role.replace("override:", "")
            layer = tables.get(parent_role)
            if layer is None:
                if optional:
                    result.choices[name] = "skipped(no parent layer)"
                    continue
                raise RuntimeError(
                    f"'{name}' needs parent "
                    f"'{definition.parentLayerParameterName()}' "
                    f"(resolved to '{parent_role}'), which is not a fixture")
            field_name, why = _pick_field(name, layer, parent_role)
            values[name] = field_name
            result.choices[name] = f"{why}@{parent_role}"
            continue

        # QgsProcessingParameterVectorLayer is a sibling of FeatureSource, not a
        # subclass, so both need the same branch.
        if isinstance(definition, (QgsProcessingParameterFeatureSource,
                                   QgsProcessingParameterVectorLayer)):
            if optional and name in SKIP_OPTIONAL:
                result.choices[name] = "skipped(optional)"
                continue
            role, why = _pick_layer(algorithm_id, name)
            if role is None:
                if optional:
                    result.choices[name] = "skipped(no fixture)"
                    continue
                raise RuntimeError(f"no fixture for required layer '{name}'")
            values[name] = tables[role]
            result.choices[name] = why
            continue

        if isinstance(definition, QgsProcessingParameterMultipleLayers):
            roles = MULTI_OVERRIDES.get(name)
            if not roles:
                if optional:
                    result.choices[name] = "skipped(no fixture)"
                    continue
                raise RuntimeError(f"no fixture list for required '{name}'")
            values[name] = [tables[role] for role in roles]
            result.choices[name] = "multi:" + ",".join(roles)
            continue

        if isinstance(definition, QgsProcessingParameterRasterLayer):
            if optional and name in SKIP_OPTIONAL:
                result.choices[name] = "skipped(optional)"
                continue
            key, why = _pick_raster(name)
            values[name] = rasters[key]
            result.choices[name] = why
            continue

        if isinstance(definition, QgsProcessingParameterNumber):
            default = definition.defaultValue()
            values[name] = float(default if default is not None else 0.0)
            result.choices[name] = f"default:{values[name]:g}"
            continue

        if isinstance(definition, QgsProcessingParameterBoolean):
            values[name] = bool(definition.defaultValue())
            result.choices[name] = f"default:{values[name]}"
            continue

        if isinstance(definition, QgsProcessingParameterEnum):
            default = definition.defaultValue()
            values[name] = int(default if default is not None else 0)
            result.choices[name] = f"default:{values[name]}"
            continue

        if isinstance(definition, QgsProcessingParameterString):
            default = definition.defaultValue()
            if optional and default in (None, ""):
                result.choices[name] = "skipped(optional)"
                continue
            values[name] = "" if default is None else str(default)
            result.choices[name] = f"default:{values[name]!r}"
            continue

        if isinstance(definition, QgsProcessingParameterCrs):
            if optional and name in SKIP_OPTIONAL:
                result.choices[name] = "skipped(optional)"
                continue
            values[name] = QgsCoordinateReferenceSystem(CITY_CRS)
            result.choices[name] = f"crs:{CITY_CRS}"
            continue

        if isinstance(definition, QgsProcessingParameterExtent):
            result.choices[name] = "skipped(optional)"
            continue

        if isinstance(definition, QgsProcessingParameterDateTime):
            when = DATETIME_OVERRIDES.get(
                name, QDateTime(QDate(2026, 6, 21), QTime(12, 0)))
            values[name] = when
            result.choices[name] = f"datetime:{when.toString('yyyy-MM-dd HH:mm')}"
            continue

        if isinstance(definition, QgsProcessingParameterFile):
            if optional:
                result.choices[name] = "skipped(optional)"
                continue
            raise RuntimeError(f"no file fixture for '{name}'")

        # A new parameter type must fail loudly rather than be silently skipped.
        raise RuntimeError(
            f"unhandled parameter type {type(definition).__name__} for '{name}'")

    return values


# --------------------------------------------------------------------------
# Verification
# --------------------------------------------------------------------------


def _verify_vector(path_or_layer):
    layer = (path_or_layer if isinstance(path_or_layer, QgsVectorLayer)
             else QgsVectorLayer(str(path_or_layer), "matrix_out", "ogr"))
    if not layer.isValid():
        return False, f"did not load as a vector layer: {path_or_layer}"
    count = layer.featureCount()
    if count <= 0:
        return False, f"empty vector output (0 features): {path_or_layer}"
    return True, f"{count} feature(s)"


def _verify_raster(path_or_layer):
    import numpy as np
    from osgeo import gdal

    layer = (path_or_layer if isinstance(path_or_layer, QgsRasterLayer)
             else QgsRasterLayer(str(path_or_layer), "matrix_out", "gdal"))
    if not layer.isValid():
        return False, f"did not load as a raster layer: {path_or_layer}"
    handle = gdal.Open(layer.source(), gdal.GA_ReadOnly)
    if handle is None:
        return False, f"GDAL could not open {layer.source()}"
    band = handle.GetRasterBand(1)
    array = band.ReadAsArray()
    nodata = band.GetNoDataValue()
    handle = None
    if array is None or array.size == 0:
        return False, "the raster band is empty"
    good = np.isfinite(array)
    if nodata is not None:
        good &= array != nodata
    populated = int(good.sum())
    if populated == 0:
        return False, "no finite, non-nodata pixel in the raster"
    return True, f"{populated}/{array.size} populated pixel(s)"


def _verify_file(path):
    target = Path(str(path))
    if not target.exists():
        return False, f"not written: {path}"
    if target.stat().st_size <= 0:
        return False, f"empty file: {path}"
    if target.suffix.lower() == ".json":
        try:
            with target.open(encoding="utf-8") as handle:
                json.load(handle)
        except (OSError, ValueError) as exc:
            return False, f"the JSON does not parse: {exc}"
    return True, f"{target.stat().st_size} byte(s)"


def verify_outputs(algorithm, produced, result):
    ok = True
    for definition in algorithm.parameterDefinitions():
        if not definition.isDestination():
            continue
        name = definition.name()
        if not isinstance(definition, QgsProcessingParameterFileDestination) \
                and name not in produced:
            result.outputs[name] = "not returned by processing.run"
            ok = False
            continue
        path = produced.get(name)
        if path is None:
            result.outputs[name] = "not returned by processing.run"
            ok = False
            continue
        if isinstance(definition, QgsProcessingParameterFeatureSink):
            good, detail = _verify_vector(path)
        elif isinstance(definition, QgsProcessingParameterRasterDestination):
            good, detail = _verify_raster(path)
        else:
            good, detail = _verify_file(path)
        if not good and _is_optional(definition) \
                and (algorithm.id(), name) in CONDITIONAL_OUTPUTS:
            result.outputs[name] = f"conditional, absent: {detail}"
            continue
        result.outputs[name] = detail
        if not good:
            ok = False
    return ok


# --------------------------------------------------------------------------
# Runner
# --------------------------------------------------------------------------


def _new_context(transform_context, feedback):
    context = QgsProcessingContext()
    context.setProject(QgsProject.instance())
    context.setTransformContext(transform_context)
    context.setFeedback(feedback)
    return context


def _teardown(application):
    """Shut QGIS down, except on Windows where shutting it down is the hazard.

    OSGeo4W can access-violate during teardown after a few hundred temporary
    Processing layers even when every algorithm passed, and it can also block
    for minutes. The work is finished and the report is already out by then, so
    on Windows the process is short-circuited instead (``os._exit`` in
    :func:`main`); the same guard exists in the geostats matrix for the same
    reason.
    """
    if os.name == "nt":
        return
    try:
        application.exitQgis()
    except Exception:  # noqa: BLE001 - teardown must never change the verdict
        pass


def run_matrix(only=None, verbose=False):
    from processing.core.Processing import Processing

    from planx.provider import PlanXProvider

    application = QgsApplication([], True)
    application.initQgis()
    work_dir = tempfile.mkdtemp(prefix="planx_matrix_")
    results = []
    catalog_errors = []
    try:
        Processing.initialize()
        provider = PlanXProvider()
        QgsApplication.processingRegistry().addProvider(provider)
        import processing
        transform_context = QgsProject.instance().transformContext()

        started = time.time()
        bundle = build_fixtures(processing, work_dir, transform_context)
        fixture_seconds = time.time() - started
        tables, rasters = _load_tables(bundle)

        # Keyed by the qualified Processing id, not name(): name() is the bare
        # slug the manual anchors use, and processing.run() needs the id.
        algorithms = {algorithm.id(): algorithm
                      for algorithm in provider.algorithms()}
        unqualified = sorted(key for key in algorithms if ":" not in key)
        if unqualified:
            catalog_errors.append(
                f"{len(unqualified)} algorithm id(s) are not provider-qualified: "
                f"{unqualified[:5]}")
        if len(algorithms) < MIN_EXPECTED_CASE_COUNT:
            catalog_errors.append(
                f"the provider exposes {len(algorithms)} algorithms, "
                f"expected at least {MIN_EXPECTED_CASE_COUNT}")

        order = [name for name in RUN_FIRST if name in algorithms]
        order += [name for name in sorted(algorithms) if name not in order]
        if only:
            order = [name for name in order if name in only]
        elif len(order) != len(algorithms):
            catalog_errors.append(
                f"the sweep covers {len(order)} of {len(algorithms)} "
                f"registered algorithms")

        artifacts = {}
        for algorithm_id in order:
            algorithm = algorithms[algorithm_id]
            result = CaseResult(algorithm_id, algorithm.displayName())
            out_dir = Path(work_dir) / "outputs" / algorithm_id.split(":")[-1]
            out_dir.mkdir(parents=True, exist_ok=True)
            feedback = MatrixFeedback()
            context = _new_context(transform_context, feedback)
            values = {}
            begin = time.time()
            try:
                if algorithm_id == "planx:democity":
                    # Already executed to build the fixtures. Reuse that run so
                    # the city is generated once, and still judge the real
                    # outputs of a real execution.
                    produced = bundle["raw"]
                else:
                    values = build_inputs(algorithm, bundle, tables, rasters,
                                          artifacts, out_dir, result)
                    produced = processing.run(algorithm_id, values,
                                              context=context,
                                              feedback=feedback)
                result.ok = verify_outputs(algorithm, produced, result)
                if not result.ok:
                    result.error = "one or more outputs failed verification"
                for definition in algorithm.parameterDefinitions():
                    if definition.isDestination() and definition.name() in produced:
                        artifacts[f"{algorithm_id}/{definition.name()}"] = \
                            produced[definition.name()]
                for artifact_name, output_name, overrides in \
                        EXTRA_RUNS.get(algorithm_id, ()):
                    extra_dir = out_dir / f"extra_{artifact_name}"
                    extra_dir.mkdir(parents=True, exist_ok=True)
                    extra = dict(values)
                    extra.update(overrides)
                    # A token, not a literal: the overrides go through the same
                    # resolver as the primary inputs, so an extra run can read an
                    # artefact an earlier extra run produced.
                    for key, value in overrides.items():
                        if isinstance(value, str) and _is_token(value):
                            extra[key] = _resolve_special(value, artifacts, bundle)
                    extra[output_name] = _destination_path(
                        output_name, extra_dir, algorithm_id)
                    extra_feedback = MatrixFeedback()
                    extra_produced = processing.run(
                        algorithm_id, extra,
                        context=_new_context(transform_context, extra_feedback),
                        feedback=extra_feedback)
                    artifacts[f"extra/{artifact_name}"] = \
                        extra_produced[output_name]
                    result.extra_info[artifact_name] = extra_feedback.info[:20]
            except Exception as exc:  # noqa: BLE001 - the verdict is the report
                result.ok = False
                result.error = f"{type(exc).__name__}: {exc}"
                if verbose:
                    traceback.print_exc()
            result.seconds = time.time() - begin
            result.warnings = feedback.warnings[:20]
            # What the algorithm said it did. This is the evidence behind a
            # green cell that a count alone cannot give - a tool that reports
            # "Scored metrics: 0" produced a well-formed empty answer, and the
            # report should say so rather than let the output count imply more.
            result.info = feedback.info[:40]
            results.append(result)
            if verbose:
                mark = "ok  " if result.ok else "FAIL"
                print(f"  {mark} {algorithm_id:34s} {result.seconds:7.2f}s "
                      f"{result.error}", flush=True)
    finally:
        shutil.rmtree(work_dir, ignore_errors=True)
        _teardown(application)

    ok_count = sum(1 for item in results if item.ok)
    return {
        "qgis_version": Qgis.version(),
        "qgis_release": Qgis.releaseName(),
        "fixture_seconds": round(fixture_seconds, 3),
        "case_count": len(results),
        "ok_count": ok_count,
        "failed_count": len(results) - ok_count,
        "catalog_errors": catalog_errors,
        "failed": [{"algorithm": item.algorithm_id, "error": item.error,
                    "choices": item.choices, "outputs": item.outputs}
                   for item in results if not item.ok],
        "cases": [item.as_dict() for item in results],
    }


def main(argv=None):
    parser = argparse.ArgumentParser(description="PlanX runtime algorithm matrix")
    parser.add_argument("--only", action="append",
                        help="restrict the sweep to this algorithm id "
                             "(repeatable; mainly for timing one tool)")
    parser.add_argument("--verbose", action="store_true",
                        help="print one line per case as it runs")
    parser.add_argument("--report", help="write the full JSON report here")
    args = parser.parse_args(argv)

    payload = run_matrix(only=set(args.only) if args.only else None,
                         verbose=args.verbose)
    if args.report:
        Path(args.report).write_text(
            json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
    print("PLANX_RUNTIME_MATRIX_JSON=" + json.dumps(payload, sort_keys=True))
    verdict = "PASS" if (payload["failed_count"] == 0
                         and not payload["catalog_errors"]) else "FAIL"
    print(f"PLANX_RUNTIME_MATRIX: {verdict} "
          f"({payload['ok_count']}/{payload['case_count']})")
    for problem in payload["catalog_errors"]:
        print(f"  catalog: {problem}")
    sys.stdout.flush()
    # QGIS teardown on Windows can block for minutes after the work is done and
    # the report is out; the process is finished either way.
    os._exit(0 if verdict == "PASS" else 1)


if __name__ == "__main__":
    main()
